/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_U_DTI_H
#define _MOCK_U_DTI_H

#include "unity.h"
#include "u_dti.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_u_dti_Init(void);
void mock_u_dti_Destroy(void);
void mock_u_dti_Verify(void);




#define dti_init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_init requires _Ignore (not AndReturn)");
#define dti_init_Ignore() dti_init_CMockIgnore()
void dti_init_CMockIgnore(void);
#define dti_init_StopIgnore() dti_init_CMockStopIgnore()
void dti_init_CMockStopIgnore(void);
#define dti_init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_init requires _Expect (not AndReturn)");
#define dti_init_Expect() dti_init_CMockExpect(__LINE__)
void dti_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_dti_init_CALLBACK)(int cmock_num_calls);
void dti_init_AddCallback(CMOCK_dti_init_CALLBACK Callback);
void dti_init_Stub(CMOCK_dti_init_CALLBACK Callback);
#define dti_init_StubWithCallback dti_init_Stub
#define dti_get_rpm_Ignore() TEST_FAIL_MESSAGE("dti_get_rpm requires _IgnoreAndReturn");
#define dti_get_rpm_IgnoreAndReturn(cmock_retval) dti_get_rpm_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dti_get_rpm_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
#define dti_get_rpm_StopIgnore() dti_get_rpm_CMockStopIgnore()
void dti_get_rpm_CMockStopIgnore(void);
#define dti_get_rpm_Expect() TEST_FAIL_MESSAGE("dti_get_rpm requires _ExpectAndReturn");
#define dti_get_rpm_ExpectAndReturn(cmock_retval) dti_get_rpm_CMockExpectAndReturn(__LINE__, cmock_retval)
void dti_get_rpm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
typedef int32_t (* CMOCK_dti_get_rpm_CALLBACK)(int cmock_num_calls);
void dti_get_rpm_AddCallback(CMOCK_dti_get_rpm_CALLBACK Callback);
void dti_get_rpm_Stub(CMOCK_dti_get_rpm_CALLBACK Callback);
#define dti_get_rpm_StubWithCallback dti_get_rpm_Stub
#define dti_record_rpm_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_record_rpm requires _Ignore (not AndReturn)");
#define dti_record_rpm_Ignore() dti_record_rpm_CMockIgnore()
void dti_record_rpm_CMockIgnore(void);
#define dti_record_rpm_StopIgnore() dti_record_rpm_CMockStopIgnore()
void dti_record_rpm_CMockStopIgnore(void);
#define dti_record_rpm_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_record_rpm requires _ExpectAnyArgs (not AndReturn)");
#define dti_record_rpm_ExpectAnyArgs() dti_record_rpm_CMockExpectAnyArgs(__LINE__)
void dti_record_rpm_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_record_rpm_ExpectAndReturn(msg, cmock_retval) TEST_FAIL_MESSAGE("dti_record_rpm requires _Expect (not AndReturn)");
#define dti_record_rpm_Expect(msg) dti_record_rpm_CMockExpect(__LINE__, msg)
void dti_record_rpm_CMockExpect(UNITY_LINE_TYPE cmock_line, can_msg_t msg);
typedef void (* CMOCK_dti_record_rpm_CALLBACK)(can_msg_t msg, int cmock_num_calls);
void dti_record_rpm_AddCallback(CMOCK_dti_record_rpm_CALLBACK Callback);
void dti_record_rpm_Stub(CMOCK_dti_record_rpm_CALLBACK Callback);
#define dti_record_rpm_StubWithCallback dti_record_rpm_Stub
#define dti_record_rpm_IgnoreArg_msg() dti_record_rpm_CMockIgnoreArg_msg(__LINE__)
void dti_record_rpm_CMockIgnoreArg_msg(UNITY_LINE_TYPE cmock_line);
#define dti_get_mph_Ignore() TEST_FAIL_MESSAGE("dti_get_mph requires _IgnoreAndReturn");
#define dti_get_mph_IgnoreAndReturn(cmock_retval) dti_get_mph_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dti_get_mph_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define dti_get_mph_StopIgnore() dti_get_mph_CMockStopIgnore()
void dti_get_mph_CMockStopIgnore(void);
#define dti_get_mph_Expect() TEST_FAIL_MESSAGE("dti_get_mph requires _ExpectAndReturn");
#define dti_get_mph_ExpectAndReturn(cmock_retval) dti_get_mph_CMockExpectAndReturn(__LINE__, cmock_retval)
void dti_get_mph_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
typedef float (* CMOCK_dti_get_mph_CALLBACK)(int cmock_num_calls);
void dti_get_mph_AddCallback(CMOCK_dti_get_mph_CALLBACK Callback);
void dti_get_mph_Stub(CMOCK_dti_get_mph_CALLBACK Callback);
#define dti_get_mph_StubWithCallback dti_get_mph_Stub
#define dti_get_input_voltage_Ignore() TEST_FAIL_MESSAGE("dti_get_input_voltage requires _IgnoreAndReturn");
#define dti_get_input_voltage_IgnoreAndReturn(cmock_retval) dti_get_input_voltage_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dti_get_input_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define dti_get_input_voltage_StopIgnore() dti_get_input_voltage_CMockStopIgnore()
void dti_get_input_voltage_CMockStopIgnore(void);
#define dti_get_input_voltage_Expect() TEST_FAIL_MESSAGE("dti_get_input_voltage requires _ExpectAndReturn");
#define dti_get_input_voltage_ExpectAndReturn(cmock_retval) dti_get_input_voltage_CMockExpectAndReturn(__LINE__, cmock_retval)
void dti_get_input_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_dti_get_input_voltage_CALLBACK)(int cmock_num_calls);
void dti_get_input_voltage_AddCallback(CMOCK_dti_get_input_voltage_CALLBACK Callback);
void dti_get_input_voltage_Stub(CMOCK_dti_get_input_voltage_CALLBACK Callback);
#define dti_get_input_voltage_StubWithCallback dti_get_input_voltage_Stub
#define dti_set_torque_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_torque requires _Ignore (not AndReturn)");
#define dti_set_torque_Ignore() dti_set_torque_CMockIgnore()
void dti_set_torque_CMockIgnore(void);
#define dti_set_torque_StopIgnore() dti_set_torque_CMockStopIgnore()
void dti_set_torque_CMockStopIgnore(void);
#define dti_set_torque_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_torque requires _ExpectAnyArgs (not AndReturn)");
#define dti_set_torque_ExpectAnyArgs() dti_set_torque_CMockExpectAnyArgs(__LINE__)
void dti_set_torque_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_set_torque_ExpectAndReturn(torque, cmock_retval) TEST_FAIL_MESSAGE("dti_set_torque requires _Expect (not AndReturn)");
#define dti_set_torque_Expect(torque) dti_set_torque_CMockExpect(__LINE__, torque)
void dti_set_torque_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t torque);
typedef void (* CMOCK_dti_set_torque_CALLBACK)(int16_t torque, int cmock_num_calls);
void dti_set_torque_AddCallback(CMOCK_dti_set_torque_CALLBACK Callback);
void dti_set_torque_Stub(CMOCK_dti_set_torque_CALLBACK Callback);
#define dti_set_torque_StubWithCallback dti_set_torque_Stub
#define dti_set_torque_IgnoreArg_torque() dti_set_torque_CMockIgnoreArg_torque(__LINE__)
void dti_set_torque_CMockIgnoreArg_torque(UNITY_LINE_TYPE cmock_line);
#define dti_set_regen_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_regen requires _Ignore (not AndReturn)");
#define dti_set_regen_Ignore() dti_set_regen_CMockIgnore()
void dti_set_regen_CMockIgnore(void);
#define dti_set_regen_StopIgnore() dti_set_regen_CMockStopIgnore()
void dti_set_regen_CMockStopIgnore(void);
#define dti_set_regen_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_regen requires _ExpectAnyArgs (not AndReturn)");
#define dti_set_regen_ExpectAnyArgs() dti_set_regen_CMockExpectAnyArgs(__LINE__)
void dti_set_regen_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_set_regen_ExpectAndReturn(current_target, cmock_retval) TEST_FAIL_MESSAGE("dti_set_regen requires _Expect (not AndReturn)");
#define dti_set_regen_Expect(current_target) dti_set_regen_CMockExpect(__LINE__, current_target)
void dti_set_regen_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t current_target);
typedef void (* CMOCK_dti_set_regen_CALLBACK)(uint16_t current_target, int cmock_num_calls);
void dti_set_regen_AddCallback(CMOCK_dti_set_regen_CALLBACK Callback);
void dti_set_regen_Stub(CMOCK_dti_set_regen_CALLBACK Callback);
#define dti_set_regen_StubWithCallback dti_set_regen_Stub
#define dti_set_regen_IgnoreArg_current_target() dti_set_regen_CMockIgnoreArg_current_target(__LINE__)
void dti_set_regen_CMockIgnoreArg_current_target(UNITY_LINE_TYPE cmock_line);
#define dti_send_brake_current_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_send_brake_current requires _Ignore (not AndReturn)");
#define dti_send_brake_current_Ignore() dti_send_brake_current_CMockIgnore()
void dti_send_brake_current_CMockIgnore(void);
#define dti_send_brake_current_StopIgnore() dti_send_brake_current_CMockStopIgnore()
void dti_send_brake_current_CMockStopIgnore(void);
#define dti_send_brake_current_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_send_brake_current requires _ExpectAnyArgs (not AndReturn)");
#define dti_send_brake_current_ExpectAnyArgs() dti_send_brake_current_CMockExpectAnyArgs(__LINE__)
void dti_send_brake_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_send_brake_current_ExpectAndReturn(brake_current, cmock_retval) TEST_FAIL_MESSAGE("dti_send_brake_current requires _Expect (not AndReturn)");
#define dti_send_brake_current_Expect(brake_current) dti_send_brake_current_CMockExpect(__LINE__, brake_current)
void dti_send_brake_current_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t brake_current);
typedef void (* CMOCK_dti_send_brake_current_CALLBACK)(uint16_t brake_current, int cmock_num_calls);
void dti_send_brake_current_AddCallback(CMOCK_dti_send_brake_current_CALLBACK Callback);
void dti_send_brake_current_Stub(CMOCK_dti_send_brake_current_CALLBACK Callback);
#define dti_send_brake_current_StubWithCallback dti_send_brake_current_Stub
#define dti_send_brake_current_IgnoreArg_brake_current() dti_send_brake_current_CMockIgnoreArg_brake_current(__LINE__)
void dti_send_brake_current_CMockIgnoreArg_brake_current(UNITY_LINE_TYPE cmock_line);
#define dti_set_relative_brake_current_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_relative_brake_current requires _Ignore (not AndReturn)");
#define dti_set_relative_brake_current_Ignore() dti_set_relative_brake_current_CMockIgnore()
void dti_set_relative_brake_current_CMockIgnore(void);
#define dti_set_relative_brake_current_StopIgnore() dti_set_relative_brake_current_CMockStopIgnore()
void dti_set_relative_brake_current_CMockStopIgnore(void);
#define dti_set_relative_brake_current_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_relative_brake_current requires _ExpectAnyArgs (not AndReturn)");
#define dti_set_relative_brake_current_ExpectAnyArgs() dti_set_relative_brake_current_CMockExpectAnyArgs(__LINE__)
void dti_set_relative_brake_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_set_relative_brake_current_ExpectAndReturn(relative_brake_current, cmock_retval) TEST_FAIL_MESSAGE("dti_set_relative_brake_current requires _Expect (not AndReturn)");
#define dti_set_relative_brake_current_Expect(relative_brake_current) dti_set_relative_brake_current_CMockExpect(__LINE__, relative_brake_current)
void dti_set_relative_brake_current_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t relative_brake_current);
typedef void (* CMOCK_dti_set_relative_brake_current_CALLBACK)(int16_t relative_brake_current, int cmock_num_calls);
void dti_set_relative_brake_current_AddCallback(CMOCK_dti_set_relative_brake_current_CALLBACK Callback);
void dti_set_relative_brake_current_Stub(CMOCK_dti_set_relative_brake_current_CALLBACK Callback);
#define dti_set_relative_brake_current_StubWithCallback dti_set_relative_brake_current_Stub
#define dti_set_relative_brake_current_IgnoreArg_relative_brake_current() dti_set_relative_brake_current_CMockIgnoreArg_relative_brake_current(__LINE__)
void dti_set_relative_brake_current_CMockIgnoreArg_relative_brake_current(UNITY_LINE_TYPE cmock_line);
#define dti_set_current_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_current requires _Ignore (not AndReturn)");
#define dti_set_current_Ignore() dti_set_current_CMockIgnore()
void dti_set_current_CMockIgnore(void);
#define dti_set_current_StopIgnore() dti_set_current_CMockStopIgnore()
void dti_set_current_CMockStopIgnore(void);
#define dti_set_current_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_current requires _ExpectAnyArgs (not AndReturn)");
#define dti_set_current_ExpectAnyArgs() dti_set_current_CMockExpectAnyArgs(__LINE__)
void dti_set_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_set_current_ExpectAndReturn(current, cmock_retval) TEST_FAIL_MESSAGE("dti_set_current requires _Expect (not AndReturn)");
#define dti_set_current_Expect(current) dti_set_current_CMockExpect(__LINE__, current)
void dti_set_current_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t current);
typedef void (* CMOCK_dti_set_current_CALLBACK)(int16_t current, int cmock_num_calls);
void dti_set_current_AddCallback(CMOCK_dti_set_current_CALLBACK Callback);
void dti_set_current_Stub(CMOCK_dti_set_current_CALLBACK Callback);
#define dti_set_current_StubWithCallback dti_set_current_Stub
#define dti_set_current_IgnoreArg_current() dti_set_current_CMockIgnoreArg_current(__LINE__)
void dti_set_current_CMockIgnoreArg_current(UNITY_LINE_TYPE cmock_line);
#define dti_set_relative_current_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_relative_current requires _Ignore (not AndReturn)");
#define dti_set_relative_current_Ignore() dti_set_relative_current_CMockIgnore()
void dti_set_relative_current_CMockIgnore(void);
#define dti_set_relative_current_StopIgnore() dti_set_relative_current_CMockStopIgnore()
void dti_set_relative_current_CMockStopIgnore(void);
#define dti_set_relative_current_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_relative_current requires _ExpectAnyArgs (not AndReturn)");
#define dti_set_relative_current_ExpectAnyArgs() dti_set_relative_current_CMockExpectAnyArgs(__LINE__)
void dti_set_relative_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_set_relative_current_ExpectAndReturn(relative_current, cmock_retval) TEST_FAIL_MESSAGE("dti_set_relative_current requires _Expect (not AndReturn)");
#define dti_set_relative_current_Expect(relative_current) dti_set_relative_current_CMockExpect(__LINE__, relative_current)
void dti_set_relative_current_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t relative_current);
typedef void (* CMOCK_dti_set_relative_current_CALLBACK)(int16_t relative_current, int cmock_num_calls);
void dti_set_relative_current_AddCallback(CMOCK_dti_set_relative_current_CALLBACK Callback);
void dti_set_relative_current_Stub(CMOCK_dti_set_relative_current_CALLBACK Callback);
#define dti_set_relative_current_StubWithCallback dti_set_relative_current_Stub
#define dti_set_relative_current_IgnoreArg_relative_current() dti_set_relative_current_CMockIgnoreArg_relative_current(__LINE__)
void dti_set_relative_current_CMockIgnoreArg_relative_current(UNITY_LINE_TYPE cmock_line);
#define dti_set_drive_enable_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_drive_enable requires _Ignore (not AndReturn)");
#define dti_set_drive_enable_Ignore() dti_set_drive_enable_CMockIgnore()
void dti_set_drive_enable_CMockIgnore(void);
#define dti_set_drive_enable_StopIgnore() dti_set_drive_enable_CMockStopIgnore()
void dti_set_drive_enable_CMockStopIgnore(void);
#define dti_set_drive_enable_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_set_drive_enable requires _ExpectAnyArgs (not AndReturn)");
#define dti_set_drive_enable_ExpectAnyArgs() dti_set_drive_enable_CMockExpectAnyArgs(__LINE__)
void dti_set_drive_enable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_set_drive_enable_ExpectAndReturn(drive_enable, cmock_retval) TEST_FAIL_MESSAGE("dti_set_drive_enable requires _Expect (not AndReturn)");
#define dti_set_drive_enable_Expect(drive_enable) dti_set_drive_enable_CMockExpect(__LINE__, drive_enable)
void dti_set_drive_enable_CMockExpect(UNITY_LINE_TYPE cmock_line, bool drive_enable);
typedef void (* CMOCK_dti_set_drive_enable_CALLBACK)(bool drive_enable, int cmock_num_calls);
void dti_set_drive_enable_AddCallback(CMOCK_dti_set_drive_enable_CALLBACK Callback);
void dti_set_drive_enable_Stub(CMOCK_dti_set_drive_enable_CALLBACK Callback);
#define dti_set_drive_enable_StubWithCallback dti_set_drive_enable_Stub
#define dti_set_drive_enable_IgnoreArg_drive_enable() dti_set_drive_enable_CMockIgnoreArg_drive_enable(__LINE__)
void dti_set_drive_enable_CMockIgnoreArg_drive_enable(UNITY_LINE_TYPE cmock_line);
#define dti_record_temp_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_record_temp requires _Ignore (not AndReturn)");
#define dti_record_temp_Ignore() dti_record_temp_CMockIgnore()
void dti_record_temp_CMockIgnore(void);
#define dti_record_temp_StopIgnore() dti_record_temp_CMockStopIgnore()
void dti_record_temp_CMockStopIgnore(void);
#define dti_record_temp_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_record_temp requires _ExpectAnyArgs (not AndReturn)");
#define dti_record_temp_ExpectAnyArgs() dti_record_temp_CMockExpectAnyArgs(__LINE__)
void dti_record_temp_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_record_temp_ExpectAndReturn(msg, cmock_retval) TEST_FAIL_MESSAGE("dti_record_temp requires _Expect (not AndReturn)");
#define dti_record_temp_Expect(msg) dti_record_temp_CMockExpect(__LINE__, msg)
void dti_record_temp_CMockExpect(UNITY_LINE_TYPE cmock_line, can_msg_t msg);
typedef void (* CMOCK_dti_record_temp_CALLBACK)(can_msg_t msg, int cmock_num_calls);
void dti_record_temp_AddCallback(CMOCK_dti_record_temp_CALLBACK Callback);
void dti_record_temp_Stub(CMOCK_dti_record_temp_CALLBACK Callback);
#define dti_record_temp_StubWithCallback dti_record_temp_Stub
#define dti_record_temp_IgnoreArg_msg() dti_record_temp_CMockIgnoreArg_msg(__LINE__)
void dti_record_temp_CMockIgnoreArg_msg(UNITY_LINE_TYPE cmock_line);
#define dti_get_motor_temp_Ignore() TEST_FAIL_MESSAGE("dti_get_motor_temp requires _IgnoreAndReturn");
#define dti_get_motor_temp_IgnoreAndReturn(cmock_retval) dti_get_motor_temp_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dti_get_motor_temp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define dti_get_motor_temp_StopIgnore() dti_get_motor_temp_CMockStopIgnore()
void dti_get_motor_temp_CMockStopIgnore(void);
#define dti_get_motor_temp_Expect() TEST_FAIL_MESSAGE("dti_get_motor_temp requires _ExpectAndReturn");
#define dti_get_motor_temp_ExpectAndReturn(cmock_retval) dti_get_motor_temp_CMockExpectAndReturn(__LINE__, cmock_retval)
void dti_get_motor_temp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_dti_get_motor_temp_CALLBACK)(int cmock_num_calls);
void dti_get_motor_temp_AddCallback(CMOCK_dti_get_motor_temp_CALLBACK Callback);
void dti_get_motor_temp_Stub(CMOCK_dti_get_motor_temp_CALLBACK Callback);
#define dti_get_motor_temp_StubWithCallback dti_get_motor_temp_Stub
#define dti_get_controller_temp_Ignore() TEST_FAIL_MESSAGE("dti_get_controller_temp requires _IgnoreAndReturn");
#define dti_get_controller_temp_IgnoreAndReturn(cmock_retval) dti_get_controller_temp_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dti_get_controller_temp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define dti_get_controller_temp_StopIgnore() dti_get_controller_temp_CMockStopIgnore()
void dti_get_controller_temp_CMockStopIgnore(void);
#define dti_get_controller_temp_Expect() TEST_FAIL_MESSAGE("dti_get_controller_temp requires _ExpectAndReturn");
#define dti_get_controller_temp_ExpectAndReturn(cmock_retval) dti_get_controller_temp_CMockExpectAndReturn(__LINE__, cmock_retval)
void dti_get_controller_temp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_dti_get_controller_temp_CALLBACK)(int cmock_num_calls);
void dti_get_controller_temp_AddCallback(CMOCK_dti_get_controller_temp_CALLBACK Callback);
void dti_get_controller_temp_Stub(CMOCK_dti_get_controller_temp_CALLBACK Callback);
#define dti_get_controller_temp_StubWithCallback dti_get_controller_temp_Stub
#define dti_record_currents_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_record_currents requires _Ignore (not AndReturn)");
#define dti_record_currents_Ignore() dti_record_currents_CMockIgnore()
void dti_record_currents_CMockIgnore(void);
#define dti_record_currents_StopIgnore() dti_record_currents_CMockStopIgnore()
void dti_record_currents_CMockStopIgnore(void);
#define dti_record_currents_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("dti_record_currents requires _ExpectAnyArgs (not AndReturn)");
#define dti_record_currents_ExpectAnyArgs() dti_record_currents_CMockExpectAnyArgs(__LINE__)
void dti_record_currents_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define dti_record_currents_ExpectAndReturn(msg, cmock_retval) TEST_FAIL_MESSAGE("dti_record_currents requires _Expect (not AndReturn)");
#define dti_record_currents_Expect(msg) dti_record_currents_CMockExpect(__LINE__, msg)
void dti_record_currents_CMockExpect(UNITY_LINE_TYPE cmock_line, can_msg_t msg);
typedef void (* CMOCK_dti_record_currents_CALLBACK)(can_msg_t msg, int cmock_num_calls);
void dti_record_currents_AddCallback(CMOCK_dti_record_currents_CALLBACK Callback);
void dti_record_currents_Stub(CMOCK_dti_record_currents_CALLBACK Callback);
#define dti_record_currents_StubWithCallback dti_record_currents_Stub
#define dti_record_currents_IgnoreArg_msg() dti_record_currents_CMockIgnoreArg_msg(__LINE__)
void dti_record_currents_CMockIgnoreArg_msg(UNITY_LINE_TYPE cmock_line);
#define dti_get_dc_current_Ignore() TEST_FAIL_MESSAGE("dti_get_dc_current requires _IgnoreAndReturn");
#define dti_get_dc_current_IgnoreAndReturn(cmock_retval) dti_get_dc_current_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void dti_get_dc_current_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define dti_get_dc_current_StopIgnore() dti_get_dc_current_CMockStopIgnore()
void dti_get_dc_current_CMockStopIgnore(void);
#define dti_get_dc_current_Expect() TEST_FAIL_MESSAGE("dti_get_dc_current requires _ExpectAndReturn");
#define dti_get_dc_current_ExpectAndReturn(cmock_retval) dti_get_dc_current_CMockExpectAndReturn(__LINE__, cmock_retval)
void dti_get_dc_current_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_dti_get_dc_current_CALLBACK)(int cmock_num_calls);
void dti_get_dc_current_AddCallback(CMOCK_dti_get_dc_current_CALLBACK Callback);
void dti_get_dc_current_Stub(CMOCK_dti_get_dc_current_CALLBACK Callback);
#define dti_get_dc_current_StubWithCallback dti_get_dc_current_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
