/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_U_PERIPHERALS_H
#define _MOCK_U_PERIPHERALS_H

#include "unity.h"
#include "u_peripherals.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_u_peripherals_Init(void);
void mock_u_peripherals_Destroy(void);
void mock_u_peripherals_Verify(void);




#define peripherals_init_Ignore() TEST_FAIL_MESSAGE("peripherals_init requires _IgnoreAndReturn");
#define peripherals_init_IgnoreAndReturn(cmock_retval) peripherals_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void peripherals_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define peripherals_init_StopIgnore() peripherals_init_CMockStopIgnore()
void peripherals_init_CMockStopIgnore(void);
#define peripherals_init_Expect() TEST_FAIL_MESSAGE("peripherals_init requires _ExpectAndReturn");
#define peripherals_init_ExpectAndReturn(cmock_retval) peripherals_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void peripherals_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
typedef int (* CMOCK_peripherals_init_CALLBACK)(int cmock_num_calls);
void peripherals_init_AddCallback(CMOCK_peripherals_init_CALLBACK Callback);
void peripherals_init_Stub(CMOCK_peripherals_init_CALLBACK Callback);
#define peripherals_init_StubWithCallback peripherals_init_Stub
#define tempsensor_toggleHeater_Ignore() TEST_FAIL_MESSAGE("tempsensor_toggleHeater requires _IgnoreAndReturn");
#define tempsensor_toggleHeater_IgnoreAndReturn(cmock_retval) tempsensor_toggleHeater_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void tempsensor_toggleHeater_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define tempsensor_toggleHeater_StopIgnore() tempsensor_toggleHeater_CMockStopIgnore()
void tempsensor_toggleHeater_CMockStopIgnore(void);
#define tempsensor_toggleHeater_ExpectAnyArgs() TEST_FAIL_MESSAGE("tempsensor_toggleHeater requires _ExpectAnyArgsAndReturn");
#define tempsensor_toggleHeater_ExpectAnyArgsAndReturn(cmock_retval) tempsensor_toggleHeater_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void tempsensor_toggleHeater_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define tempsensor_toggleHeater_Expect(enable) TEST_FAIL_MESSAGE("tempsensor_toggleHeater requires _ExpectAndReturn");
#define tempsensor_toggleHeater_ExpectAndReturn(enable, cmock_retval) tempsensor_toggleHeater_CMockExpectAndReturn(__LINE__, enable, cmock_retval)
void tempsensor_toggleHeater_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool enable, int cmock_to_return);
typedef int (* CMOCK_tempsensor_toggleHeater_CALLBACK)(bool enable, int cmock_num_calls);
void tempsensor_toggleHeater_AddCallback(CMOCK_tempsensor_toggleHeater_CALLBACK Callback);
void tempsensor_toggleHeater_Stub(CMOCK_tempsensor_toggleHeater_CALLBACK Callback);
#define tempsensor_toggleHeater_StubWithCallback tempsensor_toggleHeater_Stub
#define tempsensor_toggleHeater_IgnoreArg_enable() tempsensor_toggleHeater_CMockIgnoreArg_enable(__LINE__)
void tempsensor_toggleHeater_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line);
#define tempsensor_getTemperatureAndHumidity_Ignore() TEST_FAIL_MESSAGE("tempsensor_getTemperatureAndHumidity requires _IgnoreAndReturn");
#define tempsensor_getTemperatureAndHumidity_IgnoreAndReturn(cmock_retval) tempsensor_getTemperatureAndHumidity_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void tempsensor_getTemperatureAndHumidity_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define tempsensor_getTemperatureAndHumidity_StopIgnore() tempsensor_getTemperatureAndHumidity_CMockStopIgnore()
void tempsensor_getTemperatureAndHumidity_CMockStopIgnore(void);
#define tempsensor_getTemperatureAndHumidity_ExpectAnyArgs() TEST_FAIL_MESSAGE("tempsensor_getTemperatureAndHumidity requires _ExpectAnyArgsAndReturn");
#define tempsensor_getTemperatureAndHumidity_ExpectAnyArgsAndReturn(cmock_retval) tempsensor_getTemperatureAndHumidity_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void tempsensor_getTemperatureAndHumidity_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define tempsensor_getTemperatureAndHumidity_Expect(temperature, humidity) TEST_FAIL_MESSAGE("tempsensor_getTemperatureAndHumidity requires _ExpectAndReturn");
#define tempsensor_getTemperatureAndHumidity_ExpectAndReturn(temperature, humidity, cmock_retval) tempsensor_getTemperatureAndHumidity_CMockExpectAndReturn(__LINE__, temperature, humidity, cmock_retval)
void tempsensor_getTemperatureAndHumidity_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float* temperature, float* humidity, int cmock_to_return);
typedef int (* CMOCK_tempsensor_getTemperatureAndHumidity_CALLBACK)(float* temperature, float* humidity, int cmock_num_calls);
void tempsensor_getTemperatureAndHumidity_AddCallback(CMOCK_tempsensor_getTemperatureAndHumidity_CALLBACK Callback);
void tempsensor_getTemperatureAndHumidity_Stub(CMOCK_tempsensor_getTemperatureAndHumidity_CALLBACK Callback);
#define tempsensor_getTemperatureAndHumidity_StubWithCallback tempsensor_getTemperatureAndHumidity_Stub
#define tempsensor_getTemperatureAndHumidity_IgnoreArg_temperature() tempsensor_getTemperatureAndHumidity_CMockIgnoreArg_temperature(__LINE__)
void tempsensor_getTemperatureAndHumidity_CMockIgnoreArg_temperature(UNITY_LINE_TYPE cmock_line);
#define tempsensor_getTemperatureAndHumidity_IgnoreArg_humidity() tempsensor_getTemperatureAndHumidity_CMockIgnoreArg_humidity(__LINE__)
void tempsensor_getTemperatureAndHumidity_CMockIgnoreArg_humidity(UNITY_LINE_TYPE cmock_line);
#define imu_getAcceleration_Ignore() TEST_FAIL_MESSAGE("imu_getAcceleration requires _IgnoreAndReturn");
#define imu_getAcceleration_IgnoreAndReturn(cmock_retval) imu_getAcceleration_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void imu_getAcceleration_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define imu_getAcceleration_StopIgnore() imu_getAcceleration_CMockStopIgnore()
void imu_getAcceleration_CMockStopIgnore(void);
#define imu_getAcceleration_ExpectAnyArgs() TEST_FAIL_MESSAGE("imu_getAcceleration requires _ExpectAnyArgsAndReturn");
#define imu_getAcceleration_ExpectAnyArgsAndReturn(cmock_retval) imu_getAcceleration_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void imu_getAcceleration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define imu_getAcceleration_Expect(data) TEST_FAIL_MESSAGE("imu_getAcceleration requires _ExpectAndReturn");
#define imu_getAcceleration_ExpectAndReturn(data, cmock_retval) imu_getAcceleration_CMockExpectAndReturn(__LINE__, data, cmock_retval)
void imu_getAcceleration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vector3_t* data, int cmock_to_return);
typedef int (* CMOCK_imu_getAcceleration_CALLBACK)(vector3_t* data, int cmock_num_calls);
void imu_getAcceleration_AddCallback(CMOCK_imu_getAcceleration_CALLBACK Callback);
void imu_getAcceleration_Stub(CMOCK_imu_getAcceleration_CALLBACK Callback);
#define imu_getAcceleration_StubWithCallback imu_getAcceleration_Stub
#define imu_getAcceleration_IgnoreArg_data() imu_getAcceleration_CMockIgnoreArg_data(__LINE__)
void imu_getAcceleration_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line);
#define imu_getAngularRate_Ignore() TEST_FAIL_MESSAGE("imu_getAngularRate requires _IgnoreAndReturn");
#define imu_getAngularRate_IgnoreAndReturn(cmock_retval) imu_getAngularRate_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void imu_getAngularRate_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define imu_getAngularRate_StopIgnore() imu_getAngularRate_CMockStopIgnore()
void imu_getAngularRate_CMockStopIgnore(void);
#define imu_getAngularRate_ExpectAnyArgs() TEST_FAIL_MESSAGE("imu_getAngularRate requires _ExpectAnyArgsAndReturn");
#define imu_getAngularRate_ExpectAnyArgsAndReturn(cmock_retval) imu_getAngularRate_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void imu_getAngularRate_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define imu_getAngularRate_Expect(data) TEST_FAIL_MESSAGE("imu_getAngularRate requires _ExpectAndReturn");
#define imu_getAngularRate_ExpectAndReturn(data, cmock_retval) imu_getAngularRate_CMockExpectAndReturn(__LINE__, data, cmock_retval)
void imu_getAngularRate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vector3_t* data, int cmock_to_return);
typedef int (* CMOCK_imu_getAngularRate_CALLBACK)(vector3_t* data, int cmock_num_calls);
void imu_getAngularRate_AddCallback(CMOCK_imu_getAngularRate_CALLBACK Callback);
void imu_getAngularRate_Stub(CMOCK_imu_getAngularRate_CALLBACK Callback);
#define imu_getAngularRate_StubWithCallback imu_getAngularRate_Stub
#define imu_getAngularRate_IgnoreArg_data() imu_getAngularRate_CMockIgnoreArg_data(__LINE__)
void imu_getAngularRate_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
