/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_u_peripherals.h"

static const char* CMockString_data = "data";
static const char* CMockString_enable = "enable";
static const char* CMockString_humidity = "humidity";
static const char* CMockString_imu_getAcceleration = "imu_getAcceleration";
static const char* CMockString_imu_getAngularRate = "imu_getAngularRate";
static const char* CMockString_peripherals_init = "peripherals_init";
static const char* CMockString_temperature = "temperature";
static const char* CMockString_tempsensor_getTemperatureAndHumidity = "tempsensor_getTemperatureAndHumidity";
static const char* CMockString_tempsensor_toggleHeater = "tempsensor_toggleHeater";

typedef struct _CMOCK_peripherals_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;

} CMOCK_peripherals_init_CALL_INSTANCE;

typedef struct _CMOCK_tempsensor_toggleHeater_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  bool Expected_enable;
  char IgnoreArg_enable;

} CMOCK_tempsensor_toggleHeater_CALL_INSTANCE;

typedef struct _CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  float* Expected_temperature;
  float* Expected_humidity;
  char IgnoreArg_temperature;
  char IgnoreArg_humidity;

} CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE;

typedef struct _CMOCK_imu_getAcceleration_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  vector3_t* Expected_data;
  char IgnoreArg_data;

} CMOCK_imu_getAcceleration_CALL_INSTANCE;

typedef struct _CMOCK_imu_getAngularRate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  vector3_t* Expected_data;
  char IgnoreArg_data;

} CMOCK_imu_getAngularRate_CALL_INSTANCE;

static struct mock_u_peripheralsInstance
{
  char peripherals_init_IgnoreBool;
  int peripherals_init_FinalReturn;
  char peripherals_init_CallbackBool;
  CMOCK_peripherals_init_CALLBACK peripherals_init_CallbackFunctionPointer;
  int peripherals_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE peripherals_init_CallInstance;
  char tempsensor_toggleHeater_IgnoreBool;
  int tempsensor_toggleHeater_FinalReturn;
  char tempsensor_toggleHeater_CallbackBool;
  CMOCK_tempsensor_toggleHeater_CALLBACK tempsensor_toggleHeater_CallbackFunctionPointer;
  int tempsensor_toggleHeater_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE tempsensor_toggleHeater_CallInstance;
  char tempsensor_getTemperatureAndHumidity_IgnoreBool;
  int tempsensor_getTemperatureAndHumidity_FinalReturn;
  char tempsensor_getTemperatureAndHumidity_CallbackBool;
  CMOCK_tempsensor_getTemperatureAndHumidity_CALLBACK tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer;
  int tempsensor_getTemperatureAndHumidity_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE tempsensor_getTemperatureAndHumidity_CallInstance;
  char imu_getAcceleration_IgnoreBool;
  int imu_getAcceleration_FinalReturn;
  char imu_getAcceleration_CallbackBool;
  CMOCK_imu_getAcceleration_CALLBACK imu_getAcceleration_CallbackFunctionPointer;
  int imu_getAcceleration_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE imu_getAcceleration_CallInstance;
  char imu_getAngularRate_IgnoreBool;
  int imu_getAngularRate_FinalReturn;
  char imu_getAngularRate_CallbackBool;
  CMOCK_imu_getAngularRate_CALLBACK imu_getAngularRate_CallbackFunctionPointer;
  int imu_getAngularRate_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE imu_getAngularRate_CallInstance;
} Mock;


void mock_u_peripherals_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.peripherals_init_CallInstance;
  if (Mock.peripherals_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_peripherals_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.peripherals_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.tempsensor_toggleHeater_CallInstance;
  if (Mock.tempsensor_toggleHeater_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_tempsensor_toggleHeater);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.tempsensor_toggleHeater_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.tempsensor_getTemperatureAndHumidity_CallInstance;
  if (Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_tempsensor_getTemperatureAndHumidity);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.imu_getAcceleration_CallInstance;
  if (Mock.imu_getAcceleration_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_imu_getAcceleration);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.imu_getAcceleration_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.imu_getAngularRate_CallInstance;
  if (Mock.imu_getAngularRate_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_imu_getAngularRate);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.imu_getAngularRate_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_u_peripherals_Init(void)
{
  mock_u_peripherals_Destroy();
}

void mock_u_peripherals_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int peripherals_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_peripherals_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_peripherals_init);
  cmock_call_instance = (CMOCK_peripherals_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.peripherals_init_CallInstance);
  Mock.peripherals_init_CallInstance = CMock_Guts_MemNext(Mock.peripherals_init_CallInstance);
  if (Mock.peripherals_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.peripherals_init_FinalReturn;
    Mock.peripherals_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.peripherals_init_CallbackBool &&
      Mock.peripherals_init_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.peripherals_init_CallbackFunctionPointer(Mock.peripherals_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.peripherals_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.peripherals_init_CallbackFunctionPointer(Mock.peripherals_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void peripherals_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_peripherals_init_CALL_INSTANCE));
  CMOCK_peripherals_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_peripherals_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.peripherals_init_CallInstance = CMock_Guts_MemChain(Mock.peripherals_init_CallInstance, cmock_guts_index);
  Mock.peripherals_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.peripherals_init_IgnoreBool = (char)1;
}

void peripherals_init_CMockStopIgnore(void)
{
  if(Mock.peripherals_init_IgnoreBool)
    Mock.peripherals_init_CallInstance = CMock_Guts_MemNext(Mock.peripherals_init_CallInstance);
  Mock.peripherals_init_IgnoreBool = (char)0;
}

void peripherals_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_peripherals_init_CALL_INSTANCE));
  CMOCK_peripherals_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_peripherals_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.peripherals_init_CallInstance = CMock_Guts_MemChain(Mock.peripherals_init_CallInstance, cmock_guts_index);
  Mock.peripherals_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void peripherals_init_AddCallback(CMOCK_peripherals_init_CALLBACK Callback)
{
  Mock.peripherals_init_IgnoreBool = (char)0;
  Mock.peripherals_init_CallbackBool = (char)1;
  Mock.peripherals_init_CallbackFunctionPointer = Callback;
}

void peripherals_init_Stub(CMOCK_peripherals_init_CALLBACK Callback)
{
  Mock.peripherals_init_IgnoreBool = (char)0;
  Mock.peripherals_init_CallbackBool = (char)0;
  Mock.peripherals_init_CallbackFunctionPointer = Callback;
}

int tempsensor_toggleHeater(bool enable)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_tempsensor_toggleHeater_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_tempsensor_toggleHeater);
  cmock_call_instance = (CMOCK_tempsensor_toggleHeater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.tempsensor_toggleHeater_CallInstance);
  Mock.tempsensor_toggleHeater_CallInstance = CMock_Guts_MemNext(Mock.tempsensor_toggleHeater_CallInstance);
  if (Mock.tempsensor_toggleHeater_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.tempsensor_toggleHeater_FinalReturn;
    Mock.tempsensor_toggleHeater_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.tempsensor_toggleHeater_CallbackBool &&
      Mock.tempsensor_toggleHeater_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.tempsensor_toggleHeater_CallbackFunctionPointer(enable, Mock.tempsensor_toggleHeater_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_enable)
  {
    UNITY_SET_DETAILS(CMockString_tempsensor_toggleHeater,CMockString_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enable, enable, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.tempsensor_toggleHeater_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.tempsensor_toggleHeater_CallbackFunctionPointer(enable, Mock.tempsensor_toggleHeater_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_tempsensor_toggleHeater(CMOCK_tempsensor_toggleHeater_CALL_INSTANCE* cmock_call_instance, bool enable);
void CMockExpectParameters_tempsensor_toggleHeater(CMOCK_tempsensor_toggleHeater_CALL_INSTANCE* cmock_call_instance, bool enable)
{
  cmock_call_instance->Expected_enable = enable;
  cmock_call_instance->IgnoreArg_enable = 0;
}

void tempsensor_toggleHeater_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tempsensor_toggleHeater_CALL_INSTANCE));
  CMOCK_tempsensor_toggleHeater_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_toggleHeater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tempsensor_toggleHeater_CallInstance = CMock_Guts_MemChain(Mock.tempsensor_toggleHeater_CallInstance, cmock_guts_index);
  Mock.tempsensor_toggleHeater_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.tempsensor_toggleHeater_IgnoreBool = (char)1;
}

void tempsensor_toggleHeater_CMockStopIgnore(void)
{
  if(Mock.tempsensor_toggleHeater_IgnoreBool)
    Mock.tempsensor_toggleHeater_CallInstance = CMock_Guts_MemNext(Mock.tempsensor_toggleHeater_CallInstance);
  Mock.tempsensor_toggleHeater_IgnoreBool = (char)0;
}

void tempsensor_toggleHeater_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tempsensor_toggleHeater_CALL_INSTANCE));
  CMOCK_tempsensor_toggleHeater_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_toggleHeater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tempsensor_toggleHeater_CallInstance = CMock_Guts_MemChain(Mock.tempsensor_toggleHeater_CallInstance, cmock_guts_index);
  Mock.tempsensor_toggleHeater_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void tempsensor_toggleHeater_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool enable, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tempsensor_toggleHeater_CALL_INSTANCE));
  CMOCK_tempsensor_toggleHeater_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_toggleHeater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tempsensor_toggleHeater_CallInstance = CMock_Guts_MemChain(Mock.tempsensor_toggleHeater_CallInstance, cmock_guts_index);
  Mock.tempsensor_toggleHeater_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_tempsensor_toggleHeater(cmock_call_instance, enable);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void tempsensor_toggleHeater_AddCallback(CMOCK_tempsensor_toggleHeater_CALLBACK Callback)
{
  Mock.tempsensor_toggleHeater_IgnoreBool = (char)0;
  Mock.tempsensor_toggleHeater_CallbackBool = (char)1;
  Mock.tempsensor_toggleHeater_CallbackFunctionPointer = Callback;
}

void tempsensor_toggleHeater_Stub(CMOCK_tempsensor_toggleHeater_CALLBACK Callback)
{
  Mock.tempsensor_toggleHeater_IgnoreBool = (char)0;
  Mock.tempsensor_toggleHeater_CallbackBool = (char)0;
  Mock.tempsensor_toggleHeater_CallbackFunctionPointer = Callback;
}

void tempsensor_toggleHeater_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_tempsensor_toggleHeater_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_toggleHeater_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.tempsensor_toggleHeater_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_enable = 1;
}

int tempsensor_getTemperatureAndHumidity(float* temperature, float* humidity)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_tempsensor_getTemperatureAndHumidity);
  cmock_call_instance = (CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.tempsensor_getTemperatureAndHumidity_CallInstance);
  Mock.tempsensor_getTemperatureAndHumidity_CallInstance = CMock_Guts_MemNext(Mock.tempsensor_getTemperatureAndHumidity_CallInstance);
  if (Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.tempsensor_getTemperatureAndHumidity_FinalReturn;
    Mock.tempsensor_getTemperatureAndHumidity_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.tempsensor_getTemperatureAndHumidity_CallbackBool &&
      Mock.tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer(temperature, humidity, Mock.tempsensor_getTemperatureAndHumidity_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_temperature)
  {
    UNITY_SET_DETAILS(CMockString_tempsensor_getTemperatureAndHumidity,CMockString_temperature);
    if (cmock_call_instance->Expected_temperature == NULL)
      { UNITY_TEST_ASSERT_NULL(temperature, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_FLOAT_ARRAY(cmock_call_instance->Expected_temperature, temperature, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_humidity)
  {
    UNITY_SET_DETAILS(CMockString_tempsensor_getTemperatureAndHumidity,CMockString_humidity);
    if (cmock_call_instance->Expected_humidity == NULL)
      { UNITY_TEST_ASSERT_NULL(humidity, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_FLOAT_ARRAY(cmock_call_instance->Expected_humidity, humidity, 1, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer(temperature, humidity, Mock.tempsensor_getTemperatureAndHumidity_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_tempsensor_getTemperatureAndHumidity(CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance, float* temperature, float* humidity);
void CMockExpectParameters_tempsensor_getTemperatureAndHumidity(CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance, float* temperature, float* humidity)
{
  cmock_call_instance->Expected_temperature = temperature;
  cmock_call_instance->IgnoreArg_temperature = 0;
  cmock_call_instance->Expected_humidity = humidity;
  cmock_call_instance->IgnoreArg_humidity = 0;
}

void tempsensor_getTemperatureAndHumidity_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE));
  CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tempsensor_getTemperatureAndHumidity_CallInstance = CMock_Guts_MemChain(Mock.tempsensor_getTemperatureAndHumidity_CallInstance, cmock_guts_index);
  Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool = (char)1;
}

void tempsensor_getTemperatureAndHumidity_CMockStopIgnore(void)
{
  if(Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool)
    Mock.tempsensor_getTemperatureAndHumidity_CallInstance = CMock_Guts_MemNext(Mock.tempsensor_getTemperatureAndHumidity_CallInstance);
  Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool = (char)0;
}

void tempsensor_getTemperatureAndHumidity_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE));
  CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tempsensor_getTemperatureAndHumidity_CallInstance = CMock_Guts_MemChain(Mock.tempsensor_getTemperatureAndHumidity_CallInstance, cmock_guts_index);
  Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void tempsensor_getTemperatureAndHumidity_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float* temperature, float* humidity, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE));
  CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tempsensor_getTemperatureAndHumidity_CallInstance = CMock_Guts_MemChain(Mock.tempsensor_getTemperatureAndHumidity_CallInstance, cmock_guts_index);
  Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_tempsensor_getTemperatureAndHumidity(cmock_call_instance, temperature, humidity);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void tempsensor_getTemperatureAndHumidity_AddCallback(CMOCK_tempsensor_getTemperatureAndHumidity_CALLBACK Callback)
{
  Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool = (char)0;
  Mock.tempsensor_getTemperatureAndHumidity_CallbackBool = (char)1;
  Mock.tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer = Callback;
}

void tempsensor_getTemperatureAndHumidity_Stub(CMOCK_tempsensor_getTemperatureAndHumidity_CALLBACK Callback)
{
  Mock.tempsensor_getTemperatureAndHumidity_IgnoreBool = (char)0;
  Mock.tempsensor_getTemperatureAndHumidity_CallbackBool = (char)0;
  Mock.tempsensor_getTemperatureAndHumidity_CallbackFunctionPointer = Callback;
}

void tempsensor_getTemperatureAndHumidity_CMockIgnoreArg_temperature(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.tempsensor_getTemperatureAndHumidity_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_temperature = 1;
}

void tempsensor_getTemperatureAndHumidity_CMockIgnoreArg_humidity(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE* cmock_call_instance = (CMOCK_tempsensor_getTemperatureAndHumidity_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.tempsensor_getTemperatureAndHumidity_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_humidity = 1;
}

int imu_getAcceleration(vector3_t* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_imu_getAcceleration_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_imu_getAcceleration);
  cmock_call_instance = (CMOCK_imu_getAcceleration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.imu_getAcceleration_CallInstance);
  Mock.imu_getAcceleration_CallInstance = CMock_Guts_MemNext(Mock.imu_getAcceleration_CallInstance);
  if (Mock.imu_getAcceleration_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.imu_getAcceleration_FinalReturn;
    Mock.imu_getAcceleration_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.imu_getAcceleration_CallbackBool &&
      Mock.imu_getAcceleration_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.imu_getAcceleration_CallbackFunctionPointer(data, Mock.imu_getAcceleration_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_imu_getAcceleration,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(vector3_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.imu_getAcceleration_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.imu_getAcceleration_CallbackFunctionPointer(data, Mock.imu_getAcceleration_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_imu_getAcceleration(CMOCK_imu_getAcceleration_CALL_INSTANCE* cmock_call_instance, vector3_t* data);
void CMockExpectParameters_imu_getAcceleration(CMOCK_imu_getAcceleration_CALL_INSTANCE* cmock_call_instance, vector3_t* data)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->IgnoreArg_data = 0;
}

void imu_getAcceleration_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_imu_getAcceleration_CALL_INSTANCE));
  CMOCK_imu_getAcceleration_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAcceleration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.imu_getAcceleration_CallInstance = CMock_Guts_MemChain(Mock.imu_getAcceleration_CallInstance, cmock_guts_index);
  Mock.imu_getAcceleration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.imu_getAcceleration_IgnoreBool = (char)1;
}

void imu_getAcceleration_CMockStopIgnore(void)
{
  if(Mock.imu_getAcceleration_IgnoreBool)
    Mock.imu_getAcceleration_CallInstance = CMock_Guts_MemNext(Mock.imu_getAcceleration_CallInstance);
  Mock.imu_getAcceleration_IgnoreBool = (char)0;
}

void imu_getAcceleration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_imu_getAcceleration_CALL_INSTANCE));
  CMOCK_imu_getAcceleration_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAcceleration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.imu_getAcceleration_CallInstance = CMock_Guts_MemChain(Mock.imu_getAcceleration_CallInstance, cmock_guts_index);
  Mock.imu_getAcceleration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void imu_getAcceleration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vector3_t* data, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_imu_getAcceleration_CALL_INSTANCE));
  CMOCK_imu_getAcceleration_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAcceleration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.imu_getAcceleration_CallInstance = CMock_Guts_MemChain(Mock.imu_getAcceleration_CallInstance, cmock_guts_index);
  Mock.imu_getAcceleration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_imu_getAcceleration(cmock_call_instance, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void imu_getAcceleration_AddCallback(CMOCK_imu_getAcceleration_CALLBACK Callback)
{
  Mock.imu_getAcceleration_IgnoreBool = (char)0;
  Mock.imu_getAcceleration_CallbackBool = (char)1;
  Mock.imu_getAcceleration_CallbackFunctionPointer = Callback;
}

void imu_getAcceleration_Stub(CMOCK_imu_getAcceleration_CALLBACK Callback)
{
  Mock.imu_getAcceleration_IgnoreBool = (char)0;
  Mock.imu_getAcceleration_CallbackBool = (char)0;
  Mock.imu_getAcceleration_CallbackFunctionPointer = Callback;
}

void imu_getAcceleration_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_imu_getAcceleration_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAcceleration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.imu_getAcceleration_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

int imu_getAngularRate(vector3_t* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_imu_getAngularRate_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_imu_getAngularRate);
  cmock_call_instance = (CMOCK_imu_getAngularRate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.imu_getAngularRate_CallInstance);
  Mock.imu_getAngularRate_CallInstance = CMock_Guts_MemNext(Mock.imu_getAngularRate_CallInstance);
  if (Mock.imu_getAngularRate_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.imu_getAngularRate_FinalReturn;
    Mock.imu_getAngularRate_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.imu_getAngularRate_CallbackBool &&
      Mock.imu_getAngularRate_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.imu_getAngularRate_CallbackFunctionPointer(data, Mock.imu_getAngularRate_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_imu_getAngularRate,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(vector3_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.imu_getAngularRate_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.imu_getAngularRate_CallbackFunctionPointer(data, Mock.imu_getAngularRate_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_imu_getAngularRate(CMOCK_imu_getAngularRate_CALL_INSTANCE* cmock_call_instance, vector3_t* data);
void CMockExpectParameters_imu_getAngularRate(CMOCK_imu_getAngularRate_CALL_INSTANCE* cmock_call_instance, vector3_t* data)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->IgnoreArg_data = 0;
}

void imu_getAngularRate_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_imu_getAngularRate_CALL_INSTANCE));
  CMOCK_imu_getAngularRate_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAngularRate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.imu_getAngularRate_CallInstance = CMock_Guts_MemChain(Mock.imu_getAngularRate_CallInstance, cmock_guts_index);
  Mock.imu_getAngularRate_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.imu_getAngularRate_IgnoreBool = (char)1;
}

void imu_getAngularRate_CMockStopIgnore(void)
{
  if(Mock.imu_getAngularRate_IgnoreBool)
    Mock.imu_getAngularRate_CallInstance = CMock_Guts_MemNext(Mock.imu_getAngularRate_CallInstance);
  Mock.imu_getAngularRate_IgnoreBool = (char)0;
}

void imu_getAngularRate_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_imu_getAngularRate_CALL_INSTANCE));
  CMOCK_imu_getAngularRate_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAngularRate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.imu_getAngularRate_CallInstance = CMock_Guts_MemChain(Mock.imu_getAngularRate_CallInstance, cmock_guts_index);
  Mock.imu_getAngularRate_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void imu_getAngularRate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vector3_t* data, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_imu_getAngularRate_CALL_INSTANCE));
  CMOCK_imu_getAngularRate_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAngularRate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.imu_getAngularRate_CallInstance = CMock_Guts_MemChain(Mock.imu_getAngularRate_CallInstance, cmock_guts_index);
  Mock.imu_getAngularRate_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_imu_getAngularRate(cmock_call_instance, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void imu_getAngularRate_AddCallback(CMOCK_imu_getAngularRate_CALLBACK Callback)
{
  Mock.imu_getAngularRate_IgnoreBool = (char)0;
  Mock.imu_getAngularRate_CallbackBool = (char)1;
  Mock.imu_getAngularRate_CallbackFunctionPointer = Callback;
}

void imu_getAngularRate_Stub(CMOCK_imu_getAngularRate_CALLBACK Callback)
{
  Mock.imu_getAngularRate_IgnoreBool = (char)0;
  Mock.imu_getAngularRate_CallbackBool = (char)0;
  Mock.imu_getAngularRate_CallbackFunctionPointer = Callback;
}

void imu_getAngularRate_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_imu_getAngularRate_CALL_INSTANCE* cmock_call_instance = (CMOCK_imu_getAngularRate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.imu_getAngularRate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

