/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_u_dti.h"

static const char* CMockString_brake_current = "brake_current";
static const char* CMockString_current = "current";
static const char* CMockString_current_target = "current_target";
static const char* CMockString_drive_enable = "drive_enable";
static const char* CMockString_dti_get_controller_temp = "dti_get_controller_temp";
static const char* CMockString_dti_get_dc_current = "dti_get_dc_current";
static const char* CMockString_dti_get_input_voltage = "dti_get_input_voltage";
static const char* CMockString_dti_get_motor_temp = "dti_get_motor_temp";
static const char* CMockString_dti_get_mph = "dti_get_mph";
static const char* CMockString_dti_get_rpm = "dti_get_rpm";
static const char* CMockString_dti_init = "dti_init";
static const char* CMockString_dti_record_currents = "dti_record_currents";
static const char* CMockString_dti_record_rpm = "dti_record_rpm";
static const char* CMockString_dti_record_temp = "dti_record_temp";
static const char* CMockString_dti_send_brake_current = "dti_send_brake_current";
static const char* CMockString_dti_set_current = "dti_set_current";
static const char* CMockString_dti_set_drive_enable = "dti_set_drive_enable";
static const char* CMockString_dti_set_regen = "dti_set_regen";
static const char* CMockString_dti_set_relative_brake_current = "dti_set_relative_brake_current";
static const char* CMockString_dti_set_relative_current = "dti_set_relative_current";
static const char* CMockString_dti_set_torque = "dti_set_torque";
static const char* CMockString_msg = "msg";
static const char* CMockString_relative_brake_current = "relative_brake_current";
static const char* CMockString_relative_current = "relative_current";
static const char* CMockString_torque = "torque";

typedef struct _CMOCK_dti_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_dti_init_CALL_INSTANCE;

typedef struct _CMOCK_dti_get_rpm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int32_t ReturnVal;

} CMOCK_dti_get_rpm_CALL_INSTANCE;

typedef struct _CMOCK_dti_record_rpm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  can_msg_t Expected_msg;
  char IgnoreArg_msg;

} CMOCK_dti_record_rpm_CALL_INSTANCE;

typedef struct _CMOCK_dti_get_mph_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  float ReturnVal;

} CMOCK_dti_get_mph_CALL_INSTANCE;

typedef struct _CMOCK_dti_get_input_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t ReturnVal;

} CMOCK_dti_get_input_voltage_CALL_INSTANCE;

typedef struct _CMOCK_dti_set_torque_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int16_t Expected_torque;
  char IgnoreArg_torque;

} CMOCK_dti_set_torque_CALL_INSTANCE;

typedef struct _CMOCK_dti_set_regen_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t Expected_current_target;
  char IgnoreArg_current_target;

} CMOCK_dti_set_regen_CALL_INSTANCE;

typedef struct _CMOCK_dti_send_brake_current_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t Expected_brake_current;
  char IgnoreArg_brake_current;

} CMOCK_dti_send_brake_current_CALL_INSTANCE;

typedef struct _CMOCK_dti_set_relative_brake_current_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int16_t Expected_relative_brake_current;
  char IgnoreArg_relative_brake_current;

} CMOCK_dti_set_relative_brake_current_CALL_INSTANCE;

typedef struct _CMOCK_dti_set_current_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int16_t Expected_current;
  char IgnoreArg_current;

} CMOCK_dti_set_current_CALL_INSTANCE;

typedef struct _CMOCK_dti_set_relative_current_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int16_t Expected_relative_current;
  char IgnoreArg_relative_current;

} CMOCK_dti_set_relative_current_CALL_INSTANCE;

typedef struct _CMOCK_dti_set_drive_enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool Expected_drive_enable;
  char IgnoreArg_drive_enable;

} CMOCK_dti_set_drive_enable_CALL_INSTANCE;

typedef struct _CMOCK_dti_record_temp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  can_msg_t Expected_msg;
  char IgnoreArg_msg;

} CMOCK_dti_record_temp_CALL_INSTANCE;

typedef struct _CMOCK_dti_get_motor_temp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t ReturnVal;

} CMOCK_dti_get_motor_temp_CALL_INSTANCE;

typedef struct _CMOCK_dti_get_controller_temp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t ReturnVal;

} CMOCK_dti_get_controller_temp_CALL_INSTANCE;

typedef struct _CMOCK_dti_record_currents_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  can_msg_t Expected_msg;
  char IgnoreArg_msg;

} CMOCK_dti_record_currents_CALL_INSTANCE;

typedef struct _CMOCK_dti_get_dc_current_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t ReturnVal;

} CMOCK_dti_get_dc_current_CALL_INSTANCE;

static struct mock_u_dtiInstance
{
  char dti_init_IgnoreBool;
  char dti_init_CallbackBool;
  CMOCK_dti_init_CALLBACK dti_init_CallbackFunctionPointer;
  int dti_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_init_CallInstance;
  char dti_get_rpm_IgnoreBool;
  int32_t dti_get_rpm_FinalReturn;
  char dti_get_rpm_CallbackBool;
  CMOCK_dti_get_rpm_CALLBACK dti_get_rpm_CallbackFunctionPointer;
  int dti_get_rpm_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_get_rpm_CallInstance;
  char dti_record_rpm_IgnoreBool;
  char dti_record_rpm_CallbackBool;
  CMOCK_dti_record_rpm_CALLBACK dti_record_rpm_CallbackFunctionPointer;
  int dti_record_rpm_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_record_rpm_CallInstance;
  char dti_get_mph_IgnoreBool;
  float dti_get_mph_FinalReturn;
  char dti_get_mph_CallbackBool;
  CMOCK_dti_get_mph_CALLBACK dti_get_mph_CallbackFunctionPointer;
  int dti_get_mph_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_get_mph_CallInstance;
  char dti_get_input_voltage_IgnoreBool;
  uint16_t dti_get_input_voltage_FinalReturn;
  char dti_get_input_voltage_CallbackBool;
  CMOCK_dti_get_input_voltage_CALLBACK dti_get_input_voltage_CallbackFunctionPointer;
  int dti_get_input_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_get_input_voltage_CallInstance;
  char dti_set_torque_IgnoreBool;
  char dti_set_torque_CallbackBool;
  CMOCK_dti_set_torque_CALLBACK dti_set_torque_CallbackFunctionPointer;
  int dti_set_torque_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_set_torque_CallInstance;
  char dti_set_regen_IgnoreBool;
  char dti_set_regen_CallbackBool;
  CMOCK_dti_set_regen_CALLBACK dti_set_regen_CallbackFunctionPointer;
  int dti_set_regen_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_set_regen_CallInstance;
  char dti_send_brake_current_IgnoreBool;
  char dti_send_brake_current_CallbackBool;
  CMOCK_dti_send_brake_current_CALLBACK dti_send_brake_current_CallbackFunctionPointer;
  int dti_send_brake_current_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_send_brake_current_CallInstance;
  char dti_set_relative_brake_current_IgnoreBool;
  char dti_set_relative_brake_current_CallbackBool;
  CMOCK_dti_set_relative_brake_current_CALLBACK dti_set_relative_brake_current_CallbackFunctionPointer;
  int dti_set_relative_brake_current_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_set_relative_brake_current_CallInstance;
  char dti_set_current_IgnoreBool;
  char dti_set_current_CallbackBool;
  CMOCK_dti_set_current_CALLBACK dti_set_current_CallbackFunctionPointer;
  int dti_set_current_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_set_current_CallInstance;
  char dti_set_relative_current_IgnoreBool;
  char dti_set_relative_current_CallbackBool;
  CMOCK_dti_set_relative_current_CALLBACK dti_set_relative_current_CallbackFunctionPointer;
  int dti_set_relative_current_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_set_relative_current_CallInstance;
  char dti_set_drive_enable_IgnoreBool;
  char dti_set_drive_enable_CallbackBool;
  CMOCK_dti_set_drive_enable_CALLBACK dti_set_drive_enable_CallbackFunctionPointer;
  int dti_set_drive_enable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_set_drive_enable_CallInstance;
  char dti_record_temp_IgnoreBool;
  char dti_record_temp_CallbackBool;
  CMOCK_dti_record_temp_CALLBACK dti_record_temp_CallbackFunctionPointer;
  int dti_record_temp_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_record_temp_CallInstance;
  char dti_get_motor_temp_IgnoreBool;
  uint16_t dti_get_motor_temp_FinalReturn;
  char dti_get_motor_temp_CallbackBool;
  CMOCK_dti_get_motor_temp_CALLBACK dti_get_motor_temp_CallbackFunctionPointer;
  int dti_get_motor_temp_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_get_motor_temp_CallInstance;
  char dti_get_controller_temp_IgnoreBool;
  uint16_t dti_get_controller_temp_FinalReturn;
  char dti_get_controller_temp_CallbackBool;
  CMOCK_dti_get_controller_temp_CALLBACK dti_get_controller_temp_CallbackFunctionPointer;
  int dti_get_controller_temp_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_get_controller_temp_CallInstance;
  char dti_record_currents_IgnoreBool;
  char dti_record_currents_CallbackBool;
  CMOCK_dti_record_currents_CALLBACK dti_record_currents_CallbackFunctionPointer;
  int dti_record_currents_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_record_currents_CallInstance;
  char dti_get_dc_current_IgnoreBool;
  uint16_t dti_get_dc_current_FinalReturn;
  char dti_get_dc_current_CallbackBool;
  CMOCK_dti_get_dc_current_CALLBACK dti_get_dc_current_CallbackFunctionPointer;
  int dti_get_dc_current_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE dti_get_dc_current_CallInstance;
} Mock;


void mock_u_dti_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.dti_init_CallInstance;
  if (Mock.dti_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_get_rpm_CallInstance;
  if (Mock.dti_get_rpm_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_get_rpm);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_get_rpm_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_record_rpm_CallInstance;
  if (Mock.dti_record_rpm_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_record_rpm);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_record_rpm_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_get_mph_CallInstance;
  if (Mock.dti_get_mph_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_get_mph);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_get_mph_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_get_input_voltage_CallInstance;
  if (Mock.dti_get_input_voltage_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_get_input_voltage);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_get_input_voltage_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_set_torque_CallInstance;
  if (Mock.dti_set_torque_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_set_torque);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_set_torque_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_set_regen_CallInstance;
  if (Mock.dti_set_regen_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_set_regen);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_set_regen_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_send_brake_current_CallInstance;
  if (Mock.dti_send_brake_current_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_send_brake_current);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_send_brake_current_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_set_relative_brake_current_CallInstance;
  if (Mock.dti_set_relative_brake_current_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_set_relative_brake_current);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_set_relative_brake_current_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_set_current_CallInstance;
  if (Mock.dti_set_current_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_set_current);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_set_current_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_set_relative_current_CallInstance;
  if (Mock.dti_set_relative_current_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_set_relative_current);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_set_relative_current_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_set_drive_enable_CallInstance;
  if (Mock.dti_set_drive_enable_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_set_drive_enable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_set_drive_enable_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_record_temp_CallInstance;
  if (Mock.dti_record_temp_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_record_temp);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_record_temp_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_get_motor_temp_CallInstance;
  if (Mock.dti_get_motor_temp_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_get_motor_temp);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_get_motor_temp_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_get_controller_temp_CallInstance;
  if (Mock.dti_get_controller_temp_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_get_controller_temp);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_get_controller_temp_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_record_currents_CallInstance;
  if (Mock.dti_record_currents_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_record_currents);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_record_currents_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.dti_get_dc_current_CallInstance;
  if (Mock.dti_get_dc_current_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_dti_get_dc_current);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.dti_get_dc_current_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_u_dti_Init(void)
{
  mock_u_dti_Destroy();
}

void mock_u_dti_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void dti_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_init);
  cmock_call_instance = (CMOCK_dti_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_init_CallInstance);
  Mock.dti_init_CallInstance = CMock_Guts_MemNext(Mock.dti_init_CallInstance);
  if (Mock.dti_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_init_CallbackBool &&
      Mock.dti_init_CallbackFunctionPointer != NULL)
  {
    Mock.dti_init_CallbackFunctionPointer(Mock.dti_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dti_init_CallbackFunctionPointer != NULL)
  {
    Mock.dti_init_CallbackFunctionPointer(Mock.dti_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void dti_init_CMockIgnore(void)
{
  Mock.dti_init_IgnoreBool = (char)1;
}

void dti_init_CMockStopIgnore(void)
{
  Mock.dti_init_IgnoreBool = (char)0;
}

void dti_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_init_CALL_INSTANCE));
  CMOCK_dti_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_init_CallInstance = CMock_Guts_MemChain(Mock.dti_init_CallInstance, cmock_guts_index);
  Mock.dti_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void dti_init_AddCallback(CMOCK_dti_init_CALLBACK Callback)
{
  Mock.dti_init_IgnoreBool = (char)0;
  Mock.dti_init_CallbackBool = (char)1;
  Mock.dti_init_CallbackFunctionPointer = Callback;
}

void dti_init_Stub(CMOCK_dti_init_CALLBACK Callback)
{
  Mock.dti_init_IgnoreBool = (char)0;
  Mock.dti_init_CallbackBool = (char)0;
  Mock.dti_init_CallbackFunctionPointer = Callback;
}

int32_t dti_get_rpm(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_get_rpm_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_get_rpm);
  cmock_call_instance = (CMOCK_dti_get_rpm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_get_rpm_CallInstance);
  Mock.dti_get_rpm_CallInstance = CMock_Guts_MemNext(Mock.dti_get_rpm_CallInstance);
  if (Mock.dti_get_rpm_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dti_get_rpm_FinalReturn;
    Mock.dti_get_rpm_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dti_get_rpm_CallbackBool &&
      Mock.dti_get_rpm_CallbackFunctionPointer != NULL)
  {
    int32_t cmock_cb_ret = Mock.dti_get_rpm_CallbackFunctionPointer(Mock.dti_get_rpm_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dti_get_rpm_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.dti_get_rpm_CallbackFunctionPointer(Mock.dti_get_rpm_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dti_get_rpm_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_rpm_CALL_INSTANCE));
  CMOCK_dti_get_rpm_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_rpm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_rpm_CallInstance = CMock_Guts_MemChain(Mock.dti_get_rpm_CallInstance, cmock_guts_index);
  Mock.dti_get_rpm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dti_get_rpm_IgnoreBool = (char)1;
}

void dti_get_rpm_CMockStopIgnore(void)
{
  if(Mock.dti_get_rpm_IgnoreBool)
    Mock.dti_get_rpm_CallInstance = CMock_Guts_MemNext(Mock.dti_get_rpm_CallInstance);
  Mock.dti_get_rpm_IgnoreBool = (char)0;
}

void dti_get_rpm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_rpm_CALL_INSTANCE));
  CMOCK_dti_get_rpm_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_rpm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_rpm_CallInstance = CMock_Guts_MemChain(Mock.dti_get_rpm_CallInstance, cmock_guts_index);
  Mock.dti_get_rpm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void dti_get_rpm_AddCallback(CMOCK_dti_get_rpm_CALLBACK Callback)
{
  Mock.dti_get_rpm_IgnoreBool = (char)0;
  Mock.dti_get_rpm_CallbackBool = (char)1;
  Mock.dti_get_rpm_CallbackFunctionPointer = Callback;
}

void dti_get_rpm_Stub(CMOCK_dti_get_rpm_CALLBACK Callback)
{
  Mock.dti_get_rpm_IgnoreBool = (char)0;
  Mock.dti_get_rpm_CallbackBool = (char)0;
  Mock.dti_get_rpm_CallbackFunctionPointer = Callback;
}

void dti_record_rpm(can_msg_t msg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_record_rpm_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_record_rpm);
  cmock_call_instance = (CMOCK_dti_record_rpm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_record_rpm_CallInstance);
  Mock.dti_record_rpm_CallInstance = CMock_Guts_MemNext(Mock.dti_record_rpm_CallInstance);
  if (Mock.dti_record_rpm_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_record_rpm_CallbackBool &&
      Mock.dti_record_rpm_CallbackFunctionPointer != NULL)
  {
    Mock.dti_record_rpm_CallbackFunctionPointer(msg, Mock.dti_record_rpm_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_msg)
  {
    UNITY_SET_DETAILS(CMockString_dti_record_rpm,CMockString_msg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_msg), (void*)(&msg), sizeof(can_msg_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_record_rpm_CallbackFunctionPointer != NULL)
  {
    Mock.dti_record_rpm_CallbackFunctionPointer(msg, Mock.dti_record_rpm_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_record_rpm(CMOCK_dti_record_rpm_CALL_INSTANCE* cmock_call_instance, can_msg_t msg);
void CMockExpectParameters_dti_record_rpm(CMOCK_dti_record_rpm_CALL_INSTANCE* cmock_call_instance, can_msg_t msg)
{
  memcpy((void*)(&cmock_call_instance->Expected_msg), (void*)(&msg),
         sizeof(can_msg_t[sizeof(msg) == sizeof(can_msg_t) ? 1 : -1])); /* add can_msg_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_msg = 0;
}

void dti_record_rpm_CMockIgnore(void)
{
  Mock.dti_record_rpm_IgnoreBool = (char)1;
}

void dti_record_rpm_CMockStopIgnore(void)
{
  Mock.dti_record_rpm_IgnoreBool = (char)0;
}

void dti_record_rpm_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_record_rpm_CALL_INSTANCE));
  CMOCK_dti_record_rpm_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_rpm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_record_rpm_CallInstance = CMock_Guts_MemChain(Mock.dti_record_rpm_CallInstance, cmock_guts_index);
  Mock.dti_record_rpm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_record_rpm_CMockExpect(UNITY_LINE_TYPE cmock_line, can_msg_t msg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_record_rpm_CALL_INSTANCE));
  CMOCK_dti_record_rpm_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_rpm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_record_rpm_CallInstance = CMock_Guts_MemChain(Mock.dti_record_rpm_CallInstance, cmock_guts_index);
  Mock.dti_record_rpm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_record_rpm(cmock_call_instance, msg);
}

void dti_record_rpm_AddCallback(CMOCK_dti_record_rpm_CALLBACK Callback)
{
  Mock.dti_record_rpm_IgnoreBool = (char)0;
  Mock.dti_record_rpm_CallbackBool = (char)1;
  Mock.dti_record_rpm_CallbackFunctionPointer = Callback;
}

void dti_record_rpm_Stub(CMOCK_dti_record_rpm_CALLBACK Callback)
{
  Mock.dti_record_rpm_IgnoreBool = (char)0;
  Mock.dti_record_rpm_CallbackBool = (char)0;
  Mock.dti_record_rpm_CallbackFunctionPointer = Callback;
}

void dti_record_rpm_CMockIgnoreArg_msg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_record_rpm_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_rpm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_record_rpm_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_msg = 1;
}

float dti_get_mph(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_get_mph_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_get_mph);
  cmock_call_instance = (CMOCK_dti_get_mph_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_get_mph_CallInstance);
  Mock.dti_get_mph_CallInstance = CMock_Guts_MemNext(Mock.dti_get_mph_CallInstance);
  if (Mock.dti_get_mph_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dti_get_mph_FinalReturn;
    Mock.dti_get_mph_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dti_get_mph_CallbackBool &&
      Mock.dti_get_mph_CallbackFunctionPointer != NULL)
  {
    float cmock_cb_ret = Mock.dti_get_mph_CallbackFunctionPointer(Mock.dti_get_mph_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dti_get_mph_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.dti_get_mph_CallbackFunctionPointer(Mock.dti_get_mph_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dti_get_mph_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_mph_CALL_INSTANCE));
  CMOCK_dti_get_mph_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_mph_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_mph_CallInstance = CMock_Guts_MemChain(Mock.dti_get_mph_CallInstance, cmock_guts_index);
  Mock.dti_get_mph_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dti_get_mph_IgnoreBool = (char)1;
}

void dti_get_mph_CMockStopIgnore(void)
{
  if(Mock.dti_get_mph_IgnoreBool)
    Mock.dti_get_mph_CallInstance = CMock_Guts_MemNext(Mock.dti_get_mph_CallInstance);
  Mock.dti_get_mph_IgnoreBool = (char)0;
}

void dti_get_mph_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_mph_CALL_INSTANCE));
  CMOCK_dti_get_mph_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_mph_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_mph_CallInstance = CMock_Guts_MemChain(Mock.dti_get_mph_CallInstance, cmock_guts_index);
  Mock.dti_get_mph_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void dti_get_mph_AddCallback(CMOCK_dti_get_mph_CALLBACK Callback)
{
  Mock.dti_get_mph_IgnoreBool = (char)0;
  Mock.dti_get_mph_CallbackBool = (char)1;
  Mock.dti_get_mph_CallbackFunctionPointer = Callback;
}

void dti_get_mph_Stub(CMOCK_dti_get_mph_CALLBACK Callback)
{
  Mock.dti_get_mph_IgnoreBool = (char)0;
  Mock.dti_get_mph_CallbackBool = (char)0;
  Mock.dti_get_mph_CallbackFunctionPointer = Callback;
}

uint16_t dti_get_input_voltage(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_get_input_voltage_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_get_input_voltage);
  cmock_call_instance = (CMOCK_dti_get_input_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_get_input_voltage_CallInstance);
  Mock.dti_get_input_voltage_CallInstance = CMock_Guts_MemNext(Mock.dti_get_input_voltage_CallInstance);
  if (Mock.dti_get_input_voltage_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dti_get_input_voltage_FinalReturn;
    Mock.dti_get_input_voltage_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dti_get_input_voltage_CallbackBool &&
      Mock.dti_get_input_voltage_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.dti_get_input_voltage_CallbackFunctionPointer(Mock.dti_get_input_voltage_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dti_get_input_voltage_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.dti_get_input_voltage_CallbackFunctionPointer(Mock.dti_get_input_voltage_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dti_get_input_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_input_voltage_CALL_INSTANCE));
  CMOCK_dti_get_input_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_input_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_input_voltage_CallInstance = CMock_Guts_MemChain(Mock.dti_get_input_voltage_CallInstance, cmock_guts_index);
  Mock.dti_get_input_voltage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dti_get_input_voltage_IgnoreBool = (char)1;
}

void dti_get_input_voltage_CMockStopIgnore(void)
{
  if(Mock.dti_get_input_voltage_IgnoreBool)
    Mock.dti_get_input_voltage_CallInstance = CMock_Guts_MemNext(Mock.dti_get_input_voltage_CallInstance);
  Mock.dti_get_input_voltage_IgnoreBool = (char)0;
}

void dti_get_input_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_input_voltage_CALL_INSTANCE));
  CMOCK_dti_get_input_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_input_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_input_voltage_CallInstance = CMock_Guts_MemChain(Mock.dti_get_input_voltage_CallInstance, cmock_guts_index);
  Mock.dti_get_input_voltage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void dti_get_input_voltage_AddCallback(CMOCK_dti_get_input_voltage_CALLBACK Callback)
{
  Mock.dti_get_input_voltage_IgnoreBool = (char)0;
  Mock.dti_get_input_voltage_CallbackBool = (char)1;
  Mock.dti_get_input_voltage_CallbackFunctionPointer = Callback;
}

void dti_get_input_voltage_Stub(CMOCK_dti_get_input_voltage_CALLBACK Callback)
{
  Mock.dti_get_input_voltage_IgnoreBool = (char)0;
  Mock.dti_get_input_voltage_CallbackBool = (char)0;
  Mock.dti_get_input_voltage_CallbackFunctionPointer = Callback;
}

void dti_set_torque(int16_t torque)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_set_torque_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_set_torque);
  cmock_call_instance = (CMOCK_dti_set_torque_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_set_torque_CallInstance);
  Mock.dti_set_torque_CallInstance = CMock_Guts_MemNext(Mock.dti_set_torque_CallInstance);
  if (Mock.dti_set_torque_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_set_torque_CallbackBool &&
      Mock.dti_set_torque_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_torque_CallbackFunctionPointer(torque, Mock.dti_set_torque_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_torque)
  {
    UNITY_SET_DETAILS(CMockString_dti_set_torque,CMockString_torque);
    UNITY_TEST_ASSERT_EQUAL_INT16(cmock_call_instance->Expected_torque, torque, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_set_torque_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_torque_CallbackFunctionPointer(torque, Mock.dti_set_torque_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_set_torque(CMOCK_dti_set_torque_CALL_INSTANCE* cmock_call_instance, int16_t torque);
void CMockExpectParameters_dti_set_torque(CMOCK_dti_set_torque_CALL_INSTANCE* cmock_call_instance, int16_t torque)
{
  cmock_call_instance->Expected_torque = torque;
  cmock_call_instance->IgnoreArg_torque = 0;
}

void dti_set_torque_CMockIgnore(void)
{
  Mock.dti_set_torque_IgnoreBool = (char)1;
}

void dti_set_torque_CMockStopIgnore(void)
{
  Mock.dti_set_torque_IgnoreBool = (char)0;
}

void dti_set_torque_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_torque_CALL_INSTANCE));
  CMOCK_dti_set_torque_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_torque_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_torque_CallInstance = CMock_Guts_MemChain(Mock.dti_set_torque_CallInstance, cmock_guts_index);
  Mock.dti_set_torque_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_set_torque_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t torque)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_torque_CALL_INSTANCE));
  CMOCK_dti_set_torque_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_torque_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_torque_CallInstance = CMock_Guts_MemChain(Mock.dti_set_torque_CallInstance, cmock_guts_index);
  Mock.dti_set_torque_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_set_torque(cmock_call_instance, torque);
}

void dti_set_torque_AddCallback(CMOCK_dti_set_torque_CALLBACK Callback)
{
  Mock.dti_set_torque_IgnoreBool = (char)0;
  Mock.dti_set_torque_CallbackBool = (char)1;
  Mock.dti_set_torque_CallbackFunctionPointer = Callback;
}

void dti_set_torque_Stub(CMOCK_dti_set_torque_CALLBACK Callback)
{
  Mock.dti_set_torque_IgnoreBool = (char)0;
  Mock.dti_set_torque_CallbackBool = (char)0;
  Mock.dti_set_torque_CallbackFunctionPointer = Callback;
}

void dti_set_torque_CMockIgnoreArg_torque(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_set_torque_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_torque_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_set_torque_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_torque = 1;
}

void dti_set_regen(uint16_t current_target)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_set_regen_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_set_regen);
  cmock_call_instance = (CMOCK_dti_set_regen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_set_regen_CallInstance);
  Mock.dti_set_regen_CallInstance = CMock_Guts_MemNext(Mock.dti_set_regen_CallInstance);
  if (Mock.dti_set_regen_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_set_regen_CallbackBool &&
      Mock.dti_set_regen_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_regen_CallbackFunctionPointer(current_target, Mock.dti_set_regen_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_current_target)
  {
    UNITY_SET_DETAILS(CMockString_dti_set_regen,CMockString_current_target);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_current_target, current_target, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_set_regen_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_regen_CallbackFunctionPointer(current_target, Mock.dti_set_regen_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_set_regen(CMOCK_dti_set_regen_CALL_INSTANCE* cmock_call_instance, uint16_t current_target);
void CMockExpectParameters_dti_set_regen(CMOCK_dti_set_regen_CALL_INSTANCE* cmock_call_instance, uint16_t current_target)
{
  cmock_call_instance->Expected_current_target = current_target;
  cmock_call_instance->IgnoreArg_current_target = 0;
}

void dti_set_regen_CMockIgnore(void)
{
  Mock.dti_set_regen_IgnoreBool = (char)1;
}

void dti_set_regen_CMockStopIgnore(void)
{
  Mock.dti_set_regen_IgnoreBool = (char)0;
}

void dti_set_regen_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_regen_CALL_INSTANCE));
  CMOCK_dti_set_regen_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_regen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_regen_CallInstance = CMock_Guts_MemChain(Mock.dti_set_regen_CallInstance, cmock_guts_index);
  Mock.dti_set_regen_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_set_regen_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t current_target)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_regen_CALL_INSTANCE));
  CMOCK_dti_set_regen_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_regen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_regen_CallInstance = CMock_Guts_MemChain(Mock.dti_set_regen_CallInstance, cmock_guts_index);
  Mock.dti_set_regen_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_set_regen(cmock_call_instance, current_target);
}

void dti_set_regen_AddCallback(CMOCK_dti_set_regen_CALLBACK Callback)
{
  Mock.dti_set_regen_IgnoreBool = (char)0;
  Mock.dti_set_regen_CallbackBool = (char)1;
  Mock.dti_set_regen_CallbackFunctionPointer = Callback;
}

void dti_set_regen_Stub(CMOCK_dti_set_regen_CALLBACK Callback)
{
  Mock.dti_set_regen_IgnoreBool = (char)0;
  Mock.dti_set_regen_CallbackBool = (char)0;
  Mock.dti_set_regen_CallbackFunctionPointer = Callback;
}

void dti_set_regen_CMockIgnoreArg_current_target(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_set_regen_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_regen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_set_regen_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_current_target = 1;
}

void dti_send_brake_current(uint16_t brake_current)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_send_brake_current_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_send_brake_current);
  cmock_call_instance = (CMOCK_dti_send_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_send_brake_current_CallInstance);
  Mock.dti_send_brake_current_CallInstance = CMock_Guts_MemNext(Mock.dti_send_brake_current_CallInstance);
  if (Mock.dti_send_brake_current_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_send_brake_current_CallbackBool &&
      Mock.dti_send_brake_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_send_brake_current_CallbackFunctionPointer(brake_current, Mock.dti_send_brake_current_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_brake_current)
  {
    UNITY_SET_DETAILS(CMockString_dti_send_brake_current,CMockString_brake_current);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_brake_current, brake_current, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_send_brake_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_send_brake_current_CallbackFunctionPointer(brake_current, Mock.dti_send_brake_current_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_send_brake_current(CMOCK_dti_send_brake_current_CALL_INSTANCE* cmock_call_instance, uint16_t brake_current);
void CMockExpectParameters_dti_send_brake_current(CMOCK_dti_send_brake_current_CALL_INSTANCE* cmock_call_instance, uint16_t brake_current)
{
  cmock_call_instance->Expected_brake_current = brake_current;
  cmock_call_instance->IgnoreArg_brake_current = 0;
}

void dti_send_brake_current_CMockIgnore(void)
{
  Mock.dti_send_brake_current_IgnoreBool = (char)1;
}

void dti_send_brake_current_CMockStopIgnore(void)
{
  Mock.dti_send_brake_current_IgnoreBool = (char)0;
}

void dti_send_brake_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_send_brake_current_CALL_INSTANCE));
  CMOCK_dti_send_brake_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_send_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_send_brake_current_CallInstance = CMock_Guts_MemChain(Mock.dti_send_brake_current_CallInstance, cmock_guts_index);
  Mock.dti_send_brake_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_send_brake_current_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t brake_current)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_send_brake_current_CALL_INSTANCE));
  CMOCK_dti_send_brake_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_send_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_send_brake_current_CallInstance = CMock_Guts_MemChain(Mock.dti_send_brake_current_CallInstance, cmock_guts_index);
  Mock.dti_send_brake_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_send_brake_current(cmock_call_instance, brake_current);
}

void dti_send_brake_current_AddCallback(CMOCK_dti_send_brake_current_CALLBACK Callback)
{
  Mock.dti_send_brake_current_IgnoreBool = (char)0;
  Mock.dti_send_brake_current_CallbackBool = (char)1;
  Mock.dti_send_brake_current_CallbackFunctionPointer = Callback;
}

void dti_send_brake_current_Stub(CMOCK_dti_send_brake_current_CALLBACK Callback)
{
  Mock.dti_send_brake_current_IgnoreBool = (char)0;
  Mock.dti_send_brake_current_CallbackBool = (char)0;
  Mock.dti_send_brake_current_CallbackFunctionPointer = Callback;
}

void dti_send_brake_current_CMockIgnoreArg_brake_current(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_send_brake_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_send_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_send_brake_current_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_brake_current = 1;
}

void dti_set_relative_brake_current(int16_t relative_brake_current)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_set_relative_brake_current_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_set_relative_brake_current);
  cmock_call_instance = (CMOCK_dti_set_relative_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_set_relative_brake_current_CallInstance);
  Mock.dti_set_relative_brake_current_CallInstance = CMock_Guts_MemNext(Mock.dti_set_relative_brake_current_CallInstance);
  if (Mock.dti_set_relative_brake_current_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_set_relative_brake_current_CallbackBool &&
      Mock.dti_set_relative_brake_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_relative_brake_current_CallbackFunctionPointer(relative_brake_current, Mock.dti_set_relative_brake_current_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_relative_brake_current)
  {
    UNITY_SET_DETAILS(CMockString_dti_set_relative_brake_current,CMockString_relative_brake_current);
    UNITY_TEST_ASSERT_EQUAL_INT16(cmock_call_instance->Expected_relative_brake_current, relative_brake_current, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_set_relative_brake_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_relative_brake_current_CallbackFunctionPointer(relative_brake_current, Mock.dti_set_relative_brake_current_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_set_relative_brake_current(CMOCK_dti_set_relative_brake_current_CALL_INSTANCE* cmock_call_instance, int16_t relative_brake_current);
void CMockExpectParameters_dti_set_relative_brake_current(CMOCK_dti_set_relative_brake_current_CALL_INSTANCE* cmock_call_instance, int16_t relative_brake_current)
{
  cmock_call_instance->Expected_relative_brake_current = relative_brake_current;
  cmock_call_instance->IgnoreArg_relative_brake_current = 0;
}

void dti_set_relative_brake_current_CMockIgnore(void)
{
  Mock.dti_set_relative_brake_current_IgnoreBool = (char)1;
}

void dti_set_relative_brake_current_CMockStopIgnore(void)
{
  Mock.dti_set_relative_brake_current_IgnoreBool = (char)0;
}

void dti_set_relative_brake_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_relative_brake_current_CALL_INSTANCE));
  CMOCK_dti_set_relative_brake_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_relative_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_relative_brake_current_CallInstance = CMock_Guts_MemChain(Mock.dti_set_relative_brake_current_CallInstance, cmock_guts_index);
  Mock.dti_set_relative_brake_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_set_relative_brake_current_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t relative_brake_current)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_relative_brake_current_CALL_INSTANCE));
  CMOCK_dti_set_relative_brake_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_relative_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_relative_brake_current_CallInstance = CMock_Guts_MemChain(Mock.dti_set_relative_brake_current_CallInstance, cmock_guts_index);
  Mock.dti_set_relative_brake_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_set_relative_brake_current(cmock_call_instance, relative_brake_current);
}

void dti_set_relative_brake_current_AddCallback(CMOCK_dti_set_relative_brake_current_CALLBACK Callback)
{
  Mock.dti_set_relative_brake_current_IgnoreBool = (char)0;
  Mock.dti_set_relative_brake_current_CallbackBool = (char)1;
  Mock.dti_set_relative_brake_current_CallbackFunctionPointer = Callback;
}

void dti_set_relative_brake_current_Stub(CMOCK_dti_set_relative_brake_current_CALLBACK Callback)
{
  Mock.dti_set_relative_brake_current_IgnoreBool = (char)0;
  Mock.dti_set_relative_brake_current_CallbackBool = (char)0;
  Mock.dti_set_relative_brake_current_CallbackFunctionPointer = Callback;
}

void dti_set_relative_brake_current_CMockIgnoreArg_relative_brake_current(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_set_relative_brake_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_relative_brake_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_set_relative_brake_current_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_relative_brake_current = 1;
}

void dti_set_current(int16_t current)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_set_current_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_set_current);
  cmock_call_instance = (CMOCK_dti_set_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_set_current_CallInstance);
  Mock.dti_set_current_CallInstance = CMock_Guts_MemNext(Mock.dti_set_current_CallInstance);
  if (Mock.dti_set_current_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_set_current_CallbackBool &&
      Mock.dti_set_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_current_CallbackFunctionPointer(current, Mock.dti_set_current_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_current)
  {
    UNITY_SET_DETAILS(CMockString_dti_set_current,CMockString_current);
    UNITY_TEST_ASSERT_EQUAL_INT16(cmock_call_instance->Expected_current, current, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_set_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_current_CallbackFunctionPointer(current, Mock.dti_set_current_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_set_current(CMOCK_dti_set_current_CALL_INSTANCE* cmock_call_instance, int16_t current);
void CMockExpectParameters_dti_set_current(CMOCK_dti_set_current_CALL_INSTANCE* cmock_call_instance, int16_t current)
{
  cmock_call_instance->Expected_current = current;
  cmock_call_instance->IgnoreArg_current = 0;
}

void dti_set_current_CMockIgnore(void)
{
  Mock.dti_set_current_IgnoreBool = (char)1;
}

void dti_set_current_CMockStopIgnore(void)
{
  Mock.dti_set_current_IgnoreBool = (char)0;
}

void dti_set_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_current_CALL_INSTANCE));
  CMOCK_dti_set_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_current_CallInstance = CMock_Guts_MemChain(Mock.dti_set_current_CallInstance, cmock_guts_index);
  Mock.dti_set_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_set_current_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t current)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_current_CALL_INSTANCE));
  CMOCK_dti_set_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_current_CallInstance = CMock_Guts_MemChain(Mock.dti_set_current_CallInstance, cmock_guts_index);
  Mock.dti_set_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_set_current(cmock_call_instance, current);
}

void dti_set_current_AddCallback(CMOCK_dti_set_current_CALLBACK Callback)
{
  Mock.dti_set_current_IgnoreBool = (char)0;
  Mock.dti_set_current_CallbackBool = (char)1;
  Mock.dti_set_current_CallbackFunctionPointer = Callback;
}

void dti_set_current_Stub(CMOCK_dti_set_current_CALLBACK Callback)
{
  Mock.dti_set_current_IgnoreBool = (char)0;
  Mock.dti_set_current_CallbackBool = (char)0;
  Mock.dti_set_current_CallbackFunctionPointer = Callback;
}

void dti_set_current_CMockIgnoreArg_current(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_set_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_set_current_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_current = 1;
}

void dti_set_relative_current(int16_t relative_current)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_set_relative_current_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_set_relative_current);
  cmock_call_instance = (CMOCK_dti_set_relative_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_set_relative_current_CallInstance);
  Mock.dti_set_relative_current_CallInstance = CMock_Guts_MemNext(Mock.dti_set_relative_current_CallInstance);
  if (Mock.dti_set_relative_current_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_set_relative_current_CallbackBool &&
      Mock.dti_set_relative_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_relative_current_CallbackFunctionPointer(relative_current, Mock.dti_set_relative_current_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_relative_current)
  {
    UNITY_SET_DETAILS(CMockString_dti_set_relative_current,CMockString_relative_current);
    UNITY_TEST_ASSERT_EQUAL_INT16(cmock_call_instance->Expected_relative_current, relative_current, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_set_relative_current_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_relative_current_CallbackFunctionPointer(relative_current, Mock.dti_set_relative_current_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_set_relative_current(CMOCK_dti_set_relative_current_CALL_INSTANCE* cmock_call_instance, int16_t relative_current);
void CMockExpectParameters_dti_set_relative_current(CMOCK_dti_set_relative_current_CALL_INSTANCE* cmock_call_instance, int16_t relative_current)
{
  cmock_call_instance->Expected_relative_current = relative_current;
  cmock_call_instance->IgnoreArg_relative_current = 0;
}

void dti_set_relative_current_CMockIgnore(void)
{
  Mock.dti_set_relative_current_IgnoreBool = (char)1;
}

void dti_set_relative_current_CMockStopIgnore(void)
{
  Mock.dti_set_relative_current_IgnoreBool = (char)0;
}

void dti_set_relative_current_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_relative_current_CALL_INSTANCE));
  CMOCK_dti_set_relative_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_relative_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_relative_current_CallInstance = CMock_Guts_MemChain(Mock.dti_set_relative_current_CallInstance, cmock_guts_index);
  Mock.dti_set_relative_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_set_relative_current_CMockExpect(UNITY_LINE_TYPE cmock_line, int16_t relative_current)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_relative_current_CALL_INSTANCE));
  CMOCK_dti_set_relative_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_relative_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_relative_current_CallInstance = CMock_Guts_MemChain(Mock.dti_set_relative_current_CallInstance, cmock_guts_index);
  Mock.dti_set_relative_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_set_relative_current(cmock_call_instance, relative_current);
}

void dti_set_relative_current_AddCallback(CMOCK_dti_set_relative_current_CALLBACK Callback)
{
  Mock.dti_set_relative_current_IgnoreBool = (char)0;
  Mock.dti_set_relative_current_CallbackBool = (char)1;
  Mock.dti_set_relative_current_CallbackFunctionPointer = Callback;
}

void dti_set_relative_current_Stub(CMOCK_dti_set_relative_current_CALLBACK Callback)
{
  Mock.dti_set_relative_current_IgnoreBool = (char)0;
  Mock.dti_set_relative_current_CallbackBool = (char)0;
  Mock.dti_set_relative_current_CallbackFunctionPointer = Callback;
}

void dti_set_relative_current_CMockIgnoreArg_relative_current(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_set_relative_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_relative_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_set_relative_current_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_relative_current = 1;
}

void dti_set_drive_enable(bool drive_enable)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_set_drive_enable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_set_drive_enable);
  cmock_call_instance = (CMOCK_dti_set_drive_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_set_drive_enable_CallInstance);
  Mock.dti_set_drive_enable_CallInstance = CMock_Guts_MemNext(Mock.dti_set_drive_enable_CallInstance);
  if (Mock.dti_set_drive_enable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_set_drive_enable_CallbackBool &&
      Mock.dti_set_drive_enable_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_drive_enable_CallbackFunctionPointer(drive_enable, Mock.dti_set_drive_enable_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_drive_enable)
  {
    UNITY_SET_DETAILS(CMockString_dti_set_drive_enable,CMockString_drive_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_drive_enable, drive_enable, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_set_drive_enable_CallbackFunctionPointer != NULL)
  {
    Mock.dti_set_drive_enable_CallbackFunctionPointer(drive_enable, Mock.dti_set_drive_enable_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_set_drive_enable(CMOCK_dti_set_drive_enable_CALL_INSTANCE* cmock_call_instance, bool drive_enable);
void CMockExpectParameters_dti_set_drive_enable(CMOCK_dti_set_drive_enable_CALL_INSTANCE* cmock_call_instance, bool drive_enable)
{
  cmock_call_instance->Expected_drive_enable = drive_enable;
  cmock_call_instance->IgnoreArg_drive_enable = 0;
}

void dti_set_drive_enable_CMockIgnore(void)
{
  Mock.dti_set_drive_enable_IgnoreBool = (char)1;
}

void dti_set_drive_enable_CMockStopIgnore(void)
{
  Mock.dti_set_drive_enable_IgnoreBool = (char)0;
}

void dti_set_drive_enable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_drive_enable_CALL_INSTANCE));
  CMOCK_dti_set_drive_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_drive_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_drive_enable_CallInstance = CMock_Guts_MemChain(Mock.dti_set_drive_enable_CallInstance, cmock_guts_index);
  Mock.dti_set_drive_enable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_set_drive_enable_CMockExpect(UNITY_LINE_TYPE cmock_line, bool drive_enable)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_set_drive_enable_CALL_INSTANCE));
  CMOCK_dti_set_drive_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_drive_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_set_drive_enable_CallInstance = CMock_Guts_MemChain(Mock.dti_set_drive_enable_CallInstance, cmock_guts_index);
  Mock.dti_set_drive_enable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_set_drive_enable(cmock_call_instance, drive_enable);
}

void dti_set_drive_enable_AddCallback(CMOCK_dti_set_drive_enable_CALLBACK Callback)
{
  Mock.dti_set_drive_enable_IgnoreBool = (char)0;
  Mock.dti_set_drive_enable_CallbackBool = (char)1;
  Mock.dti_set_drive_enable_CallbackFunctionPointer = Callback;
}

void dti_set_drive_enable_Stub(CMOCK_dti_set_drive_enable_CALLBACK Callback)
{
  Mock.dti_set_drive_enable_IgnoreBool = (char)0;
  Mock.dti_set_drive_enable_CallbackBool = (char)0;
  Mock.dti_set_drive_enable_CallbackFunctionPointer = Callback;
}

void dti_set_drive_enable_CMockIgnoreArg_drive_enable(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_set_drive_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_set_drive_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_set_drive_enable_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_drive_enable = 1;
}

void dti_record_temp(can_msg_t msg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_record_temp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_record_temp);
  cmock_call_instance = (CMOCK_dti_record_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_record_temp_CallInstance);
  Mock.dti_record_temp_CallInstance = CMock_Guts_MemNext(Mock.dti_record_temp_CallInstance);
  if (Mock.dti_record_temp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_record_temp_CallbackBool &&
      Mock.dti_record_temp_CallbackFunctionPointer != NULL)
  {
    Mock.dti_record_temp_CallbackFunctionPointer(msg, Mock.dti_record_temp_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_msg)
  {
    UNITY_SET_DETAILS(CMockString_dti_record_temp,CMockString_msg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_msg), (void*)(&msg), sizeof(can_msg_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_record_temp_CallbackFunctionPointer != NULL)
  {
    Mock.dti_record_temp_CallbackFunctionPointer(msg, Mock.dti_record_temp_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_record_temp(CMOCK_dti_record_temp_CALL_INSTANCE* cmock_call_instance, can_msg_t msg);
void CMockExpectParameters_dti_record_temp(CMOCK_dti_record_temp_CALL_INSTANCE* cmock_call_instance, can_msg_t msg)
{
  memcpy((void*)(&cmock_call_instance->Expected_msg), (void*)(&msg),
         sizeof(can_msg_t[sizeof(msg) == sizeof(can_msg_t) ? 1 : -1])); /* add can_msg_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_msg = 0;
}

void dti_record_temp_CMockIgnore(void)
{
  Mock.dti_record_temp_IgnoreBool = (char)1;
}

void dti_record_temp_CMockStopIgnore(void)
{
  Mock.dti_record_temp_IgnoreBool = (char)0;
}

void dti_record_temp_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_record_temp_CALL_INSTANCE));
  CMOCK_dti_record_temp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_record_temp_CallInstance = CMock_Guts_MemChain(Mock.dti_record_temp_CallInstance, cmock_guts_index);
  Mock.dti_record_temp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_record_temp_CMockExpect(UNITY_LINE_TYPE cmock_line, can_msg_t msg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_record_temp_CALL_INSTANCE));
  CMOCK_dti_record_temp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_record_temp_CallInstance = CMock_Guts_MemChain(Mock.dti_record_temp_CallInstance, cmock_guts_index);
  Mock.dti_record_temp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_record_temp(cmock_call_instance, msg);
}

void dti_record_temp_AddCallback(CMOCK_dti_record_temp_CALLBACK Callback)
{
  Mock.dti_record_temp_IgnoreBool = (char)0;
  Mock.dti_record_temp_CallbackBool = (char)1;
  Mock.dti_record_temp_CallbackFunctionPointer = Callback;
}

void dti_record_temp_Stub(CMOCK_dti_record_temp_CALLBACK Callback)
{
  Mock.dti_record_temp_IgnoreBool = (char)0;
  Mock.dti_record_temp_CallbackBool = (char)0;
  Mock.dti_record_temp_CallbackFunctionPointer = Callback;
}

void dti_record_temp_CMockIgnoreArg_msg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_record_temp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_record_temp_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_msg = 1;
}

uint16_t dti_get_motor_temp(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_get_motor_temp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_get_motor_temp);
  cmock_call_instance = (CMOCK_dti_get_motor_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_get_motor_temp_CallInstance);
  Mock.dti_get_motor_temp_CallInstance = CMock_Guts_MemNext(Mock.dti_get_motor_temp_CallInstance);
  if (Mock.dti_get_motor_temp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dti_get_motor_temp_FinalReturn;
    Mock.dti_get_motor_temp_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dti_get_motor_temp_CallbackBool &&
      Mock.dti_get_motor_temp_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.dti_get_motor_temp_CallbackFunctionPointer(Mock.dti_get_motor_temp_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dti_get_motor_temp_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.dti_get_motor_temp_CallbackFunctionPointer(Mock.dti_get_motor_temp_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dti_get_motor_temp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_motor_temp_CALL_INSTANCE));
  CMOCK_dti_get_motor_temp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_motor_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_motor_temp_CallInstance = CMock_Guts_MemChain(Mock.dti_get_motor_temp_CallInstance, cmock_guts_index);
  Mock.dti_get_motor_temp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dti_get_motor_temp_IgnoreBool = (char)1;
}

void dti_get_motor_temp_CMockStopIgnore(void)
{
  if(Mock.dti_get_motor_temp_IgnoreBool)
    Mock.dti_get_motor_temp_CallInstance = CMock_Guts_MemNext(Mock.dti_get_motor_temp_CallInstance);
  Mock.dti_get_motor_temp_IgnoreBool = (char)0;
}

void dti_get_motor_temp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_motor_temp_CALL_INSTANCE));
  CMOCK_dti_get_motor_temp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_motor_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_motor_temp_CallInstance = CMock_Guts_MemChain(Mock.dti_get_motor_temp_CallInstance, cmock_guts_index);
  Mock.dti_get_motor_temp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void dti_get_motor_temp_AddCallback(CMOCK_dti_get_motor_temp_CALLBACK Callback)
{
  Mock.dti_get_motor_temp_IgnoreBool = (char)0;
  Mock.dti_get_motor_temp_CallbackBool = (char)1;
  Mock.dti_get_motor_temp_CallbackFunctionPointer = Callback;
}

void dti_get_motor_temp_Stub(CMOCK_dti_get_motor_temp_CALLBACK Callback)
{
  Mock.dti_get_motor_temp_IgnoreBool = (char)0;
  Mock.dti_get_motor_temp_CallbackBool = (char)0;
  Mock.dti_get_motor_temp_CallbackFunctionPointer = Callback;
}

uint16_t dti_get_controller_temp(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_get_controller_temp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_get_controller_temp);
  cmock_call_instance = (CMOCK_dti_get_controller_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_get_controller_temp_CallInstance);
  Mock.dti_get_controller_temp_CallInstance = CMock_Guts_MemNext(Mock.dti_get_controller_temp_CallInstance);
  if (Mock.dti_get_controller_temp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dti_get_controller_temp_FinalReturn;
    Mock.dti_get_controller_temp_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dti_get_controller_temp_CallbackBool &&
      Mock.dti_get_controller_temp_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.dti_get_controller_temp_CallbackFunctionPointer(Mock.dti_get_controller_temp_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dti_get_controller_temp_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.dti_get_controller_temp_CallbackFunctionPointer(Mock.dti_get_controller_temp_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dti_get_controller_temp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_controller_temp_CALL_INSTANCE));
  CMOCK_dti_get_controller_temp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_controller_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_controller_temp_CallInstance = CMock_Guts_MemChain(Mock.dti_get_controller_temp_CallInstance, cmock_guts_index);
  Mock.dti_get_controller_temp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dti_get_controller_temp_IgnoreBool = (char)1;
}

void dti_get_controller_temp_CMockStopIgnore(void)
{
  if(Mock.dti_get_controller_temp_IgnoreBool)
    Mock.dti_get_controller_temp_CallInstance = CMock_Guts_MemNext(Mock.dti_get_controller_temp_CallInstance);
  Mock.dti_get_controller_temp_IgnoreBool = (char)0;
}

void dti_get_controller_temp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_controller_temp_CALL_INSTANCE));
  CMOCK_dti_get_controller_temp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_controller_temp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_controller_temp_CallInstance = CMock_Guts_MemChain(Mock.dti_get_controller_temp_CallInstance, cmock_guts_index);
  Mock.dti_get_controller_temp_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void dti_get_controller_temp_AddCallback(CMOCK_dti_get_controller_temp_CALLBACK Callback)
{
  Mock.dti_get_controller_temp_IgnoreBool = (char)0;
  Mock.dti_get_controller_temp_CallbackBool = (char)1;
  Mock.dti_get_controller_temp_CallbackFunctionPointer = Callback;
}

void dti_get_controller_temp_Stub(CMOCK_dti_get_controller_temp_CALLBACK Callback)
{
  Mock.dti_get_controller_temp_IgnoreBool = (char)0;
  Mock.dti_get_controller_temp_CallbackBool = (char)0;
  Mock.dti_get_controller_temp_CallbackFunctionPointer = Callback;
}

void dti_record_currents(can_msg_t msg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_record_currents_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_record_currents);
  cmock_call_instance = (CMOCK_dti_record_currents_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_record_currents_CallInstance);
  Mock.dti_record_currents_CallInstance = CMock_Guts_MemNext(Mock.dti_record_currents_CallInstance);
  if (Mock.dti_record_currents_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.dti_record_currents_CallbackBool &&
      Mock.dti_record_currents_CallbackFunctionPointer != NULL)
  {
    Mock.dti_record_currents_CallbackFunctionPointer(msg, Mock.dti_record_currents_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_msg)
  {
    UNITY_SET_DETAILS(CMockString_dti_record_currents,CMockString_msg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_msg), (void*)(&msg), sizeof(can_msg_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.dti_record_currents_CallbackFunctionPointer != NULL)
  {
    Mock.dti_record_currents_CallbackFunctionPointer(msg, Mock.dti_record_currents_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dti_record_currents(CMOCK_dti_record_currents_CALL_INSTANCE* cmock_call_instance, can_msg_t msg);
void CMockExpectParameters_dti_record_currents(CMOCK_dti_record_currents_CALL_INSTANCE* cmock_call_instance, can_msg_t msg)
{
  memcpy((void*)(&cmock_call_instance->Expected_msg), (void*)(&msg),
         sizeof(can_msg_t[sizeof(msg) == sizeof(can_msg_t) ? 1 : -1])); /* add can_msg_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_msg = 0;
}

void dti_record_currents_CMockIgnore(void)
{
  Mock.dti_record_currents_IgnoreBool = (char)1;
}

void dti_record_currents_CMockStopIgnore(void)
{
  Mock.dti_record_currents_IgnoreBool = (char)0;
}

void dti_record_currents_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_record_currents_CALL_INSTANCE));
  CMOCK_dti_record_currents_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_currents_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_record_currents_CallInstance = CMock_Guts_MemChain(Mock.dti_record_currents_CallInstance, cmock_guts_index);
  Mock.dti_record_currents_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void dti_record_currents_CMockExpect(UNITY_LINE_TYPE cmock_line, can_msg_t msg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_record_currents_CALL_INSTANCE));
  CMOCK_dti_record_currents_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_currents_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_record_currents_CallInstance = CMock_Guts_MemChain(Mock.dti_record_currents_CallInstance, cmock_guts_index);
  Mock.dti_record_currents_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_dti_record_currents(cmock_call_instance, msg);
}

void dti_record_currents_AddCallback(CMOCK_dti_record_currents_CALLBACK Callback)
{
  Mock.dti_record_currents_IgnoreBool = (char)0;
  Mock.dti_record_currents_CallbackBool = (char)1;
  Mock.dti_record_currents_CallbackFunctionPointer = Callback;
}

void dti_record_currents_Stub(CMOCK_dti_record_currents_CALLBACK Callback)
{
  Mock.dti_record_currents_IgnoreBool = (char)0;
  Mock.dti_record_currents_CallbackBool = (char)0;
  Mock.dti_record_currents_CallbackFunctionPointer = Callback;
}

void dti_record_currents_CMockIgnoreArg_msg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_dti_record_currents_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_record_currents_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.dti_record_currents_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_msg = 1;
}

uint16_t dti_get_dc_current(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dti_get_dc_current_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dti_get_dc_current);
  cmock_call_instance = (CMOCK_dti_get_dc_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dti_get_dc_current_CallInstance);
  Mock.dti_get_dc_current_CallInstance = CMock_Guts_MemNext(Mock.dti_get_dc_current_CallInstance);
  if (Mock.dti_get_dc_current_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dti_get_dc_current_FinalReturn;
    Mock.dti_get_dc_current_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.dti_get_dc_current_CallbackBool &&
      Mock.dti_get_dc_current_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.dti_get_dc_current_CallbackFunctionPointer(Mock.dti_get_dc_current_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.dti_get_dc_current_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.dti_get_dc_current_CallbackFunctionPointer(Mock.dti_get_dc_current_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dti_get_dc_current_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_dc_current_CALL_INSTANCE));
  CMOCK_dti_get_dc_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_dc_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_dc_current_CallInstance = CMock_Guts_MemChain(Mock.dti_get_dc_current_CallInstance, cmock_guts_index);
  Mock.dti_get_dc_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dti_get_dc_current_IgnoreBool = (char)1;
}

void dti_get_dc_current_CMockStopIgnore(void)
{
  if(Mock.dti_get_dc_current_IgnoreBool)
    Mock.dti_get_dc_current_CallInstance = CMock_Guts_MemNext(Mock.dti_get_dc_current_CallInstance);
  Mock.dti_get_dc_current_IgnoreBool = (char)0;
}

void dti_get_dc_current_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dti_get_dc_current_CALL_INSTANCE));
  CMOCK_dti_get_dc_current_CALL_INSTANCE* cmock_call_instance = (CMOCK_dti_get_dc_current_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dti_get_dc_current_CallInstance = CMock_Guts_MemChain(Mock.dti_get_dc_current_CallInstance, cmock_guts_index);
  Mock.dti_get_dc_current_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void dti_get_dc_current_AddCallback(CMOCK_dti_get_dc_current_CALLBACK Callback)
{
  Mock.dti_get_dc_current_IgnoreBool = (char)0;
  Mock.dti_get_dc_current_CallbackBool = (char)1;
  Mock.dti_get_dc_current_CallbackFunctionPointer = Callback;
}

void dti_get_dc_current_Stub(CMOCK_dti_get_dc_current_CALLBACK Callback)
{
  Mock.dti_get_dc_current_IgnoreBool = (char)0;
  Mock.dti_get_dc_current_CallbackBool = (char)0;
  Mock.dti_get_dc_current_CallbackFunctionPointer = Callback;
}

