#ifndef _CAN_MSGS_TX_H
#define _CAN_MSGS_TX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/
#include <stdbool.h>
#include <stdint.h>

/**
* Contents of this message:
* VCU/eFuses/Dashboard/ADC - Raw ADC Value.
* VCU/eFuses/Dashboard/Voltage - Dashboard eFuse Voltage
* VCU/eFuses/Dashboard/Current - Dashboard eFuse Current.
* VCU/eFuses/Dashboard/Faulted? - The state of the Dashboard eFuse's fault pin.
* VCU/eFuses/Dashboard/Enabled? - The state of the Dashboard eFuse's Enable pin.
*/
uint8_t send_dashboard_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/Brake/ADC - Raw ADC Value.
* VCU/eFuses/Brake/Voltage - Brake eFuse Voltage
* VCU/eFuses/Brake/Current - Brake eFuse Current.
* VCU/eFuses/Brake/Faulted? - The state of the Brake eFuse's fault pin.
* VCU/eFuses/Brake/Enabled? - The state of the Brake eFuse's Enable pin.
*/
uint8_t send_brake_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/Shutdown/ADC - Raw ADC Value.
* VCU/eFuses/Shutdown/Voltage - Shutdown eFuse Voltage
* VCU/eFuses/Shutdown/Current - Shutdown eFuse Current.
* VCU/eFuses/Shutdown/Faulted? - The state of the Shutdown eFuse's fault pin.
* VCU/eFuses/Shutdown/Enabled? - The state of the Shutdown eFuse's Enable pin.
*/
uint8_t send_shutdown_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/LV/ADC - Raw ADC Value.
* VCU/eFuses/LV/Voltage - LV eFuse Voltage
* VCU/eFuses/LV/Current - LV eFuse Current.
* VCU/eFuses/LV/Faulted? - The state of the LV eFuse's fault pin.
* VCU/eFuses/LV/Enabled? - The state of the LV eFuse's Enable pin.
*/
uint8_t send_lv_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/Radfan/ADC - Raw ADC Value.
* VCU/eFuses/Radfan/Voltage - Radfan eFuse Voltage
* VCU/eFuses/Radfan/Current - Radfan eFuse Current.
* VCU/eFuses/Radfan/Faulted? - The state of the Radfan eFuse's fault pin.
* VCU/eFuses/Radfan/Enabled? - The state of the Radfan eFuse's Enable pin.
*/
uint8_t send_radfan_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/Fanbatt/ADC - Raw ADC Value.
* VCU/eFuses/Fanbatt/Voltage - Fanbatt eFuse Voltage
* VCU/eFuses/Fanbatt/Current - Fanbatt eFuse Current.
* VCU/eFuses/Fanbatt/Faulted? - The state of the Fanbatt eFuse's fault pin.
* VCU/eFuses/Fanbatt/Enabled? - The state of the Fanbatt eFuse's Enable pin.
*/
uint8_t send_fanbatt_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/PumpOne/ADC - Raw ADC Value.
* VCU/eFuses/PumpOne/Voltage - PumpOne eFuse Voltage
* VCU/eFuses/PumpOne/Current - PumpOne eFuse Current.
* VCU/eFuses/PumpOne/Faulted? - The state of the PumpOne eFuse's fault pin.
* VCU/eFuses/PumpOne/Enabled? - The state of the PumpOne eFuse's Enable pin.
*/
uint8_t send_pumpone_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/PumpTwo/ADC - Raw ADC Value.
* VCU/eFuses/PumpTwo/Voltage - PumpTwo eFuse Voltage
* VCU/eFuses/PumpTwo/Current - PumpTwo eFuse Current.
* VCU/eFuses/PumpTwo/Faulted? - The state of the PumpTwo eFuse's fault pin.
* VCU/eFuses/PumpTwo/Enabled? - The state of the PumpTwo eFuse's Enable pin.
*/
uint8_t send_pumptwo_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/Battbox/ADC - Raw ADC Value.
* VCU/eFuses/Battbox/Voltage - Battbox eFuse Voltage
* VCU/eFuses/Battbox/Current - Battbox eFuse Current.
* VCU/eFuses/Battbox/Faulted? - The state of the Battbox eFuse's fault pin.
* VCU/eFuses/Battbox/Enabled? - The state of the Battbox eFuse's Enable pin.
*/
uint8_t send_battbox_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/eFuses/MC/ADC - Raw ADC Value.
* VCU/eFuses/MC/Voltage - MC eFuse Voltage
* VCU/eFuses/MC/Current - MC eFuse Current.
* VCU/eFuses/MC/Faulted? - The state of the MC eFuse's fault pin.
* VCU/eFuses/MC/Enabled? - The state of the MC eFuse's Enable pin.
*/
uint8_t send_mc_efuse
(uint16_t ADC,float voltage,float current,bool is_faulted,bool is_enabled);

/**
* Contents of this message:
* VCU/Shutdown/BMS_GPIO - 
* VCU/Shutdown/BOTS_GPIO - 
* VCU/Shutdown/SPARE_GPIO - 
* VCU/Shutdown/BSPD_GPIO - 
* VCU/Shutdown/HV_C_GPIO - 
* VCU/Shutdown/HVD_GPIO - 
* VCU/Shutdown/IMD_GPIO - 
* VCU/Shutdown/CKPT_GPIO - 
* VCU/Shutdown/INERTIA_SW_GPIO - 
* VCU/Shutdown/TSMS_GPIO - 
*/
uint8_t send_shutdown_pins
(bool bms_gpio,bool bots_gpio,bool spare_gpio,bool bspd_gpio,bool hv_c,bool hvd_gpio,bool imd_gpio,bool ckpt_gpio,bool inertia_sw_gpio,bool tsms_gpio,uint8_t UNUSED);

/**
* Contents of this message:
* VCU/Faults/ONBOARD_PEDAL_OPEN_CIRCUIT_FAULT - Onboard Pedal Open Circuit Fault.
* VCU/Faults/ONBOARD_PEDAL_SHORT_CIRCUIT_FAULT - Onboard Pedal Short Circuit Fault.
* VCU/Faults/ONBOARD_PEDAL_DIFFERENCE_FAULT - Onboard Pedal Difference Fault.
* VCU/Faults/CAN_DISPATCH_FAULT - CAN Dispatch Fault
* VCU/Faults/CAN_ROUTING_FAULT - CAN Routing Fault.
* VCU/Faults/BMS_CAN_MONITOR_FAULT - BMS CAN Monitor Fault.
* VCU/Faults/ONBOARD_TEMP_FAULT - Onboard Temperature Fault.
* VCU/Faults/IMU_FAULT - IMU Fault.
* VCU/Faults/FUSE_MONITOR_FAULT - Fuse Monitor Fault
* VCU/Faults/SHUTDOWN_MONITOR_FAULT - Shutdown Monitor Fault.
* VCU/Faults/LV_MONITOR_FAULT - LV Monitor Fault
* VCU/Faults/BSPD_PREFAULT - BSPD Prefault.
* VCU/Faults/RTDS_FAULT - RTDS Fault.
* VCU/Faults/PUMP_SENSORS_FAULT - Pump Sensors Fault.
* VCU/Faults/PDU_CURRENT_FAULT - PDU Current Fault.
*/
uint8_t send_faults
(bool ONBOARD_PEDAL_OPEN_CIRCUIT_FAULT,bool ONBOARD_PEDAL_SHORT_CIRCUIT_FAULT,bool ONBOARD_PEDAL_DIFFERENCE_FAULT,bool CAN_DISPATCH_FAULT,bool CAN_ROUTING_FAULT,bool BMS_CAN_MONITOR_FAULT,bool ONBOARD_TEMP_FAULT,bool IMU_FAULT,bool FUSE_MONITOR_FAULT,bool SHUTDOWN_MONITOR_FAULT,bool LV_MONITOR_FAULT,bool BSPD_PREFAULT,bool RTDS_FAULT,bool PUMP_SENSORS_FAULT,bool PDU_CURRENT_FAULT);

/**
* Contents of this message:
* VCU/CarState/home_mode - Whether or not VCU is in home mode.
* VCU/CarState/nero_index - VCU's current nero_index value.
* VCU/CarState/speed - Speed of the car, in miles per hour.
* VCU/CarState/tsms - Whether or not shutdown is closed.
* VCU/CarState/torque_limit_percentage - The torque limit selected by the driver.
* VCU/CarState/not_in_reverse - Whether or not the car is in reverse.
* VCU/CarState/regen_limit - The regenerative braking current limit (selected by the driver).
* VCU/CarState/launch_control - Whether or not launch control is enabled.
*/
uint8_t send_car_state
(bool home_mode,uint8_t nero_index,int32_t car_speed,bool tsms,uint32_t torque_limit_percentage,bool reverse,uint16_t regen_limit,bool launch_control);

/**
* Contents of this message:
* VCU/Pedals/Percentages/acceleration_pedal - How far the acceleration pedal is pressed, ranging from 0 to 1.
* VCU/Pedals/Percentages/brake_pedal - How far the brake pedal is pressed, ranging from 0 to 1.
*/
uint8_t send_pedal_percent_pressed_values
(uint16_t accel_norm,uint16_t brake_norm);

/**
* Contents of this message:
* VCU/Pedals/Voltages/accel_1 - Voltage reading from Acceleration Pedal Sensor 1
* VCU/Pedals/Voltages/accel_2 - Voltage reading from Acceleration Pedal Sensor 2
* VCU/Pedals/Voltages/brake_1 - Voltage reading from Brake Pedal Sensor 1
* VCU/Pedals/Voltages/brake_2 - Voltage reading from Brake Pedal Sensor 2
*/
uint8_t send_pedal_sensor_voltages
(uint16_t accel1_volts,uint16_t accel2_volts,uint16_t brake1_volts,uint16_t brake2_volts);

/**
* Contents of this message:
* VCU/Lightning/Status - Lightning Board Light Status.
*/
uint8_t send_lightning_board_light_status
(uint8_t status);

/**
* Contents of this message:
* VCU/Temp/Temperature - VCU Temperature
* VCU/Temp/Humidity - VCU Humidity
*/
uint8_t send_temperature_sensor
(float vcu_temperature,float vcu_humidity);

/**
* Contents of this message:
* VCU/IMU/Accelerometer - IMU acceleration values (x,y,z).
*/
uint8_t send_imu_accelerometer
(float imu_accelerometer_x,float imu_accelerometer_y,float imu_accelerometer_z);

/**
* Contents of this message:
* VCU/IMU/Gyro - IMU Gyroscope Reading
*/
uint8_t send_imu_gyro
(float imu_gyro_x,float imu_gyro_y,float imu_gyro_z);
#endif