#ifndef _CAN_MSGS_RX_H
#define _CAN_MSGS_RX_H

/*
 * This file was autogenerated by the CGEN module of the Odyssey framework.
 * DO NOT EDIT without also reporting the edit to the Odyssey-Definitions repository to be incorproated into the generator.
*/

#include <stdbool.h>

#include "u_tx_debug.h"
#include "u_queues.h"
#include "c_utils.h"
#include "fdcan.h"
#include "bitstream.h"

typedef struct {
 float temp;
 float humidity;
} front_msb_env_t;

void receive_front_msb_env(const can_msg_t *message, front_msb_env_t *front_msb_env);

typedef struct {
 float x_force;
 float y_force;
 float z_force;
} front_msb_accel_t;

void receive_front_msb_accel(const can_msg_t *message, front_msb_accel_t *front_msb_accel);

typedef struct {
 float x_deg;
 float y_deg;
 float z_deg;
} front_msb_gyro_t;

void receive_front_msb_gyro(const can_msg_t *message, front_msb_gyro_t *front_msb_gyro);

typedef struct {
 uint32_t strain1;
 uint32_t strain2;
} front_msb_strain_t;

void receive_front_msb_strain(const can_msg_t *message, front_msb_strain_t *front_msb_strain);

typedef struct {
 float shock1;
 uint16_t shock1_raw;
} front_shockpot_t;

void receive_front_shockpot(const can_msg_t *message, front_shockpot_t *front_shockpot);

typedef struct {
 float rh;
} front_ride_height_t;

void receive_front_ride_height(const can_msg_t *message, front_ride_height_t *front_ride_height);

typedef struct {
 float wheel_temp;
} front_wheel_temp_t;

void receive_front_wheel_temp(const can_msg_t *message, front_wheel_temp_t *front_wheel_temp);

typedef struct {
 float x_fdeg;
 float y_fdeg;
 float z_fdeg;
} front_msb_orientation_t;

void receive_front_msb_orientation(const can_msg_t *message, front_msb_orientation_t *front_msb_orientation);

typedef struct {
 float temp;
 float humidity;
} back_msb_env_t;

void receive_back_msb_env(const can_msg_t *message, back_msb_env_t *back_msb_env);

typedef struct {
 float x_force;
 float y_force;
 float z_force;
} back_msb_accel_t;

void receive_back_msb_accel(const can_msg_t *message, back_msb_accel_t *back_msb_accel);

typedef struct {
 float x_deg;
 float y_deg;
 float z_deg;
} back_msb_gyro_t;

void receive_back_msb_gyro(const can_msg_t *message, back_msb_gyro_t *back_msb_gyro);

typedef struct {
 uint32_t strain1;
 uint32_t strain2;
} back_msb_strain_t;

void receive_back_msb_strain(const can_msg_t *message, back_msb_strain_t *back_msb_strain);

typedef struct {
 float shock1;
 uint16_t shock1_raw;
} back_shockpot_t;

void receive_back_shockpot(const can_msg_t *message, back_shockpot_t *back_shockpot);

typedef struct {
 float rh;
} back_ride_height_t;

void receive_back_ride_height(const can_msg_t *message, back_ride_height_t *back_ride_height);

typedef struct {
 float wheel_temp;
} back_wheel_temp_t;

void receive_back_wheel_temp(const can_msg_t *message, back_wheel_temp_t *back_wheel_temp);

typedef struct {
 float x_fdeg;
 float y_fdeg;
 float z_fdeg;
} back_msb_orientation_t;

void receive_back_msb_orientation(const can_msg_t *message, back_msb_orientation_t *back_msb_orientation);

typedef struct {
 float max_current_ac_target;
} max_ac_current_command_t;

void receive_max_ac_current_command(const can_msg_t *message, max_ac_current_command_t *max_ac_current_command);

typedef struct {
 float max_ac_brake_current_target;
} max_ac_brake_current_command_t;

void receive_max_ac_brake_current_command(const can_msg_t *message, max_ac_brake_current_command_t *max_ac_brake_current_command);

typedef struct {
 float max_dc_current_target;
} max_dc_current_command_t;

void receive_max_dc_current_command(const can_msg_t *message, max_dc_current_command_t *max_dc_current_command);

typedef struct {
 float max_dc_brake_current_target;
} max_dc_brake_current_command_t;

void receive_max_dc_brake_current_command(const can_msg_t *message, max_dc_brake_current_command_t *max_dc_brake_current_command);

typedef struct {
 uint8_t state;
} dashboard_efuse_state_t;

void receive_dashboard_efuse_state(const can_msg_t *message, dashboard_efuse_state_t *dashboard_efuse_state);

typedef struct {
 uint8_t state;
} brake_efuse_state_t;

void receive_brake_efuse_state(const can_msg_t *message, brake_efuse_state_t *brake_efuse_state);

typedef struct {
 uint8_t state;
} shutdown_efuse_state_t;

void receive_shutdown_efuse_state(const can_msg_t *message, shutdown_efuse_state_t *shutdown_efuse_state);

typedef struct {
 uint8_t state;
} lv_efuse_state_t;

void receive_lv_efuse_state(const can_msg_t *message, lv_efuse_state_t *lv_efuse_state);

typedef struct {
 uint8_t state;
} radfan_efuse_state_t;

void receive_radfan_efuse_state(const can_msg_t *message, radfan_efuse_state_t *radfan_efuse_state);

typedef struct {
 uint8_t state;
} fanbatt_efuse_state_t;

void receive_fanbatt_efuse_state(const can_msg_t *message, fanbatt_efuse_state_t *fanbatt_efuse_state);

typedef struct {
 uint8_t state;
} pumpone_efuse_state_t;

void receive_pumpone_efuse_state(const can_msg_t *message, pumpone_efuse_state_t *pumpone_efuse_state);

typedef struct {
 uint8_t state;
} pumptwo_efuse_state_t;

void receive_pumptwo_efuse_state(const can_msg_t *message, pumptwo_efuse_state_t *pumptwo_efuse_state);

typedef struct {
 uint8_t state;
} battbox_efuse_state_t;

void receive_battbox_efuse_state(const can_msg_t *message, battbox_efuse_state_t *battbox_efuse_state);

typedef struct {
 uint8_t state;
} mc_efuse_state_t;

void receive_mc_efuse_state(const can_msg_t *message, mc_efuse_state_t *mc_efuse_state);

typedef struct {
 uint8_t state;
} spare_efuse_state_t;

void receive_spare_efuse_state(const can_msg_t *message, spare_efuse_state_t *spare_efuse_state);

typedef struct {
 uint8_t command;
} rtds_command_message_t;

void receive_rtds_command_message(const can_msg_t *message, rtds_command_message_t *rtds_command_message);

typedef struct {
 float accel_x;
 float accel_y;
 float accel_z;
} lightning_board_imu_acceleration_data_t;

void receive_lightning_board_imu_acceleration_data(const can_msg_t *message, lightning_board_imu_acceleration_data_t *lightning_board_imu_acceleration_data);

typedef struct {
 float gyro_x;
 float gyro_y;
 float gyro_z;
} lightning_board_imu_gyro_data_t;

void receive_lightning_board_imu_gyro_data(const can_msg_t *message, lightning_board_imu_gyro_data_t *lightning_board_imu_gyro_data);

typedef struct {
 uint8_t interrupt;
 uint8_t distance;
 uint32_t energy;
} lightning_board_lightning_sensor_information_t;

void receive_lightning_board_lightning_sensor_information(const can_msg_t *message, lightning_board_lightning_sensor_information_t *lightning_board_lightning_sensor_information);

typedef struct {
 float mag_x;
 float mag_y;
 float mag_z;
} lightning_board_magnometer_sensor_information_t;

void receive_lightning_board_magnometer_sensor_information(const can_msg_t *message, lightning_board_magnometer_sensor_information_t *lightning_board_magnometer_sensor_information);

typedef struct {
 float charge_volts;
 float charge_current;
 uint8_t enable_charging;
} bms_charge_message_send_t;

void receive_bms_charge_message_send(const can_msg_t *message, bms_charge_message_send_t *bms_charge_message_send);

typedef struct {
 float voltage;
 float current;
 float amp_hours;
 float soc;
 float health;
} pack_status_t;

void receive_pack_status(const can_msg_t *message, pack_status_t *pack_status);

typedef struct {
 uint8_t state;
 float temp_average;
 float temp_internal;
} bms_status_t;

void receive_bms_status(const can_msg_t *message, bms_status_t *bms_status);

typedef struct {
 float high_val;
 uint8_t high_chip;
 uint8_t high_cell;
 float low_val;
 uint8_t low_chip;
 uint8_t low_cell;
 float avg_val;
} cell_voltage_t;

void receive_cell_voltage(const can_msg_t *message, cell_voltage_t *cell_voltage);

typedef struct {
 float high_val;
 uint8_t high_chip;
 uint8_t high_cell;
 float low_val;
 uint8_t low_chip;
 uint8_t low_cell;
 float avg_val;
} cell_temperatures_t;

void receive_cell_temperatures(const can_msg_t *message, cell_temperatures_t *cell_temperatures);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_temperatures_t;

void receive_segment_temperatures(const can_msg_t *message, segment_temperatures_t *segment_temperatures);

typedef struct {
 uint8_t state;
 uint8_t break_location;
 uint8_t verification_attempts;
 uint8_t recovery_successful;
} segment_isospi_communication_status_t;

void receive_segment_isospi_communication_status(const can_msg_t *message, segment_isospi_communication_status_t *segment_isospi_communication_status);

typedef struct {
 bool dcl_enforce;
 bool ccl_enforce;
 bool low_cell_volt;
 bool high_cell_volt;
 bool high_charge_volt;
 bool pack_hot;
 bool die_temp_max;
 bool segment_comms;
 bool hv_plate_comms;
} fault_status_t;

void receive_fault_status(const can_msg_t *message, fault_status_t *fault_status);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_average_voltages_t;

void receive_segment_average_voltages(const can_msg_t *message, segment_average_voltages_t *segment_average_voltages);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_total_voltages_t;

void receive_segment_total_voltages(const can_msg_t *message, segment_total_voltages_t *segment_total_voltages);

typedef struct {
 float seg1;
 float seg2;
 float seg3;
 float seg4;
 float seg5;
} segment_delta_voltages_t;

void receive_segment_delta_voltages(const can_msg_t *message, segment_delta_voltages_t *segment_delta_voltages);

typedef struct {
 uint8_t spare0;
 uint8_t spare1;
 uint16_t spare2;
 uint32_t spare3;
} bms_debug_t;

void receive_bms_debug(const can_msg_t *message, bms_debug_t *bms_debug);

typedef struct {
 uint8_t start_stop;
 uint8_t code;
 float value;
} bms_fault_timers_t;

void receive_bms_fault_timers(const can_msg_t *message, bms_fault_timers_t *bms_fault_timers);

typedef struct {
 uint8_t major;
 uint8_t minor;
 uint8_t patch;
 bool dirty;
 bool local_commit;
} shepherd_version_tag_t;

void receive_shepherd_version_tag(const can_msg_t *message, shepherd_version_tag_t *shepherd_version_tag);

typedef struct {
 uint32_t short_hash;
 uint32_t author_hash;
} shepherd_version_hash_t;

void receive_shepherd_version_hash(const can_msg_t *message, shepherd_version_hash_t *shepherd_version_hash);

typedef struct {
 uint32_t overflow_can_id;
 uint16_t overflow_cnt;
} overflow_notification_for_percell_t;

void receive_overflow_notification_for_percell(const can_msg_t *message, overflow_notification_for_percell_t *overflow_notification_for_percell);

typedef struct {
 float therm;
 float voltage_a;
 float voltage_b;
 uint8_t chip_id;
 uint8_t cell_a;
 uint8_t cell_b;
 bool discharging_a;
 bool discharging_b;
 bool cvs_a;
 bool cvs_b;
} alpha_cell_data_debug_t;

void receive_alpha_cell_data_debug(const can_msg_t *message, alpha_cell_data_debug_t *alpha_cell_data_debug);

typedef struct {
 float therm;
 float voltage_a;
 float voltage_b;
 uint8_t chip_id;
 uint8_t cell_a;
 uint8_t cell_b;
 bool discharging_a;
 bool discharging_b;
 bool cvs_a;
 bool cvs_b;
} beta_cell_data_debug_t;

void receive_beta_cell_data_debug(const can_msg_t *message, beta_cell_data_debug_t *beta_cell_data_debug);

typedef struct {
 uint8_t chip_id;
 float die_temp;
 float vpv;
 float vmv;
 bool va_ov;
 bool va_uv;
 bool vd_ov;
 bool vd_uv;
 bool vde;
 bool vdel;
 bool spiflt;
 bool sleep;
 bool thsd;
 bool tmodchk;
 bool oscchk;
} chip_a_debug_t;

void receive_chip_a_debug(const can_msg_t *message, chip_a_debug_t *chip_a_debug);

typedef struct {
 float vres;
 uint8_t chip_id;
 float vref2;
 float v_analog;
 float v_digital;
 bool otp1_med;
 bool opt2_med;
} chip_b_debug_t;

void receive_chip_b_debug(const can_msg_t *message, chip_b_debug_t *chip_b_debug);

typedef struct {
 uint8_t fan_duty_cycle;
} fan_duty_cycle_percentage_t;

void receive_fan_duty_cycle_percentage(const can_msg_t *message, fan_duty_cycle_percentage_t *fan_duty_cycle_percentage);

typedef struct {
 uint8_t chip_id;
 float therm_temp_1;
 float therm_temp_2;
 float therm_temp_3;
} onboard_therm_temperatures_t;

void receive_onboard_therm_temperatures(const can_msg_t *message, onboard_therm_temperatures_t *onboard_therm_temperatures);

typedef struct {
 bool precharge_status;
} precharge_status_t;

void receive_precharge_status(const can_msg_t *message, precharge_status_t *precharge_status);

typedef struct {
 float batt_voltage;
 float ts_voltage;
 float shunt_temp;
 float pack_current;
} hv_plate_data_t;

void receive_hv_plate_data(const can_msg_t *message, hv_plate_data_t *hv_plate_data);

typedef struct {
 uint8_t chip_id;
 uint16_t pec_errors;
} segment_pec_errors_t;

void receive_segment_pec_errors(const can_msg_t *message, segment_pec_errors_t *segment_pec_errors);

typedef struct {
 uint16_t pec_errors;
} hv_plate_pec_errors_t;

void receive_hv_plate_pec_errors(const can_msg_t *message, hv_plate_pec_errors_t *hv_plate_pec_errors);

typedef struct {
 uint16_t flags;
 float vreg;
 float tmp1;
 float vref1p25;
 uint16_t osccnt;
} hv_plate_diagnostics_t;

void receive_hv_plate_diagnostics(const can_msg_t *message, hv_plate_diagnostics_t *hv_plate_diagnostics);

typedef struct {
 float epad;
 float vdig;
 float vdd;
 float tmp2;
 float vdiv;
} hv_plate_diagnostics_second_t;

void receive_hv_plate_diagnostics_second(const can_msg_t *message, hv_plate_diagnostics_second_t *hv_plate_diagnostics_second);

typedef struct {
 float one;
 int16_t two;
 uint8_t three;
} bms_test_message_one_t;

void receive_bms_test_message_one(const can_msg_t *message, bms_test_message_one_t *bms_test_message_one);

typedef struct {
 uint8_t one;
 bool two;
 uint8_t three;
 uint8_t four;
 bool five;
 bool six;
 bool seven;
 bool eight;
 uint32_t nine;
 uint16_t ten;
} bms_test_message_two_t;

void receive_bms_test_message_two(const can_msg_t *message, bms_test_message_two_t *bms_test_message_two);


void receive_can(const can_msg_t *msg);

#endif