#ifndef __U_FAULTS_H
#define __U_FAULTS_H

typedef enum {

	/* START CRIT FAULTS HERE */
	CRIT_FAULT_1,
	CRIT_FAULT_2,
	CRIT_FAULT_3,
	CRIT_FAULT_4,
	CRIT_FAULT_5,
	CRIT_FAULT_6,
    CRIT_FAULT_7,
    CRIT_FAULT_8,
    CRIT_FAULT_9,
    CRIT_FAULT_10,
    CRIT_FAULT_11,
    CRIT_FAULT_12,
    CRIT_FAULT_13,
    CRIT_FAULT_14,
    CRIT_FAULT_15,
    END_CRIT_FAULTS,

	/* START NONCRIT FAULTS HERE */
    NONCRIT_FAULT_1,
	NONCRIT_FAULT_2,
    NONCRIT_FAULT_3,
    NONCRIT_FAULT_4,
    NONCRIT_FAULT_5,
    NONCRIT_FAULT_6,
    NONCRIT_FAULT_7,
    NONCRIT_FAULT_8,
    NONCRIT_FAULT_9,
    NONCRIT_FAULT_10,
    NONCRIT_FAULT_11,
    NONCRIT_FAULT_12,
    NONCRIT_FAULT_13,
    NONCRIT_FAULT_14,
    NONCRIT_FAULT_15,
    END_NONCRIT_FAULTS,

    /* Total number of faults */
    NUM_FAULTS = (END_NONCRIT_FAULTS - 1)

} fault_t;

#endif /* u_faults.h */