name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build with CMake
      run: | 
        if ! docker compose run --rm ner-gcc-arm sh -c mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .; then
        echo "The application has failed to build."
        exit 1
        fi
      
